// Auto-generated by scripts/build-sw.ts -- do not edit directly.
const SHELL_CACHE = "shell-812d0c2978a6b409";
const DATA_CACHE = "data-812d0c2978a6b409";
const STATIC_CACHE = "static-812d0c2978a6b409";
const RUNTIME_CACHE = "runtime-812d0c2978a6b409";
const CURRENT_CACHES = ["shell-812d0c2978a6b409","data-812d0c2978a6b409","static-812d0c2978a6b409","runtime-812d0c2978a6b409"];
const PRECACHE_URLS = ["/Holy-Qur-an/","/Holy-Qur-an/offline.html","/Holy-Qur-an/manifest.webmanifest","/Holy-Qur-an/icons/icon-192.png","/Holy-Qur-an/icons/icon-512.png","/Holy-Qur-an/data/v1/manifest.json","/Holy-Qur-an/data/v1/meta.json","/Holy-Qur-an/data/v1/index.json","/Holy-Qur-an/data/v1/forms.json","/Holy-Qur-an/data/v1/en-index.json","/Holy-Qur-an/data/v1/verse-roots.json"];
const BASE_PATH = "/Holy-Qur-an";
const OFFLINE_URL = "/Holy-Qur-an/offline.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((name) => !CURRENT_CACHES.includes(name))
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirstNavigation(request));
    return;
  }

  if (url.pathname.startsWith(BASE_PATH + "/data/v1/")) {
    event.respondWith(cacheFirst(request, DATA_CACHE));
    return;
  }

  if (url.pathname.startsWith(BASE_PATH + "/_next/static/")) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  event.respondWith(staleWhileRevalidate(request, RUNTIME_CACHE));
});

async function networkFirstNavigation(request) {
  try {
    const response = await fetch(request);
    const cache = await caches.open(SHELL_CACHE);
    cache.put(request, response.clone());
    return response;
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    const offline = await caches.match(OFFLINE_URL);
    if (offline) return offline;
    throw err;
  }
}

async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(cacheName);
    cache.put(request, response.clone());
  }
  return response;
}

async function staleWhileRevalidate(request, cacheName) {
  const cached = await caches.match(request);
  const fetchPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        caches.open(cacheName).then((cache) => cache.put(request, response.clone()));
      }
      return response;
    })
    .catch(() => cached);
  return cached || fetchPromise;
}
