/**
 * Postbuild step: writes out/sw.js, a hand-rolled service worker (no
 * Workbox/next-pwa -- both fight with `output: 'export'` + Turbopack).
 *
 * Strategy:
 *  - A small, fixed app-shell list is precached on install (the home page,
 *    offline fallback, manifest, icons, and the small eager data files).
 *    Next's `_next/static/**` build assets are NOT precached from a
 *    generated file list (fragile to get exactly right); they're cached
 *    lazily, cache-first, the first time each is actually requested --
 *    safe because Next fingerprints them by content hash.
 *  - `/data/v1/**` responses are cached cache-first under a cache name
 *    keyed to the data build's hash, so a new data build (new hash)
 *    naturally invalidates old cached data without an explicit purge list.
 *    This is also what makes "download everything for offline" work: the
 *    client just does ordinary `fetch()` calls (see prefetchAll in
 *    src/lib/data/loader.ts) and this same cache-first handler populates
 *    the cache as a side effect.
 *  - Navigations are network-first, falling back to the cache, falling
 *    back to /offline.html.
 *  - Everything else same-origin is stale-while-revalidate.
 *
 * NEXT_PUBLIC_BASE_PATH (set only for the GitHub Pages "project site"
 * build, e.g. "/Holy-Qur-an") is threaded through every URL below, and
 * also used to patch the two static files Next.js exports verbatim
 * (manifest.webmanifest, offline.html) since those aren't part of Next's
 * own basePath-aware asset pipeline.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ManifestFile } from "../src/lib/data/types";

const OUT_DIR = join(process.cwd(), "out");
const MANIFEST_PATH = join(OUT_DIR, "data", "v1", "manifest.json");
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

function readDataHash(): string {
  if (!existsSync(MANIFEST_PATH)) {
    console.warn("build-sw: data manifest not found, using a fallback cache version.");
    return "dev";
  }
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as ManifestFile;
  return manifest.hash;
}

function buildServiceWorker(hash: string, basePath: string): string {
  const shellCache = `shell-${hash}`;
  const dataCache = `data-${hash}`;
  const staticCache = `static-${hash}`;
  const runtimeCache = `runtime-${hash}`;
  const currentCaches = JSON.stringify([shellCache, dataCache, staticCache, runtimeCache]);

  const p = (path: string) => `${basePath}${path}`;
  const precacheUrls = JSON.stringify([
    p("/"),
    p("/offline.html"),
    p("/manifest.webmanifest"),
    p("/icons/icon-192.png"),
    p("/icons/icon-512.png"),
    p("/data/v1/manifest.json"),
    p("/data/v1/meta.json"),
    p("/data/v1/index.json"),
    p("/data/v1/forms.json"),
    p("/data/v1/en-index.json"),
  ]);

  return `// Auto-generated by scripts/build-sw.ts -- do not edit directly.
const SHELL_CACHE = ${JSON.stringify(shellCache)};
const DATA_CACHE = ${JSON.stringify(dataCache)};
const STATIC_CACHE = ${JSON.stringify(staticCache)};
const RUNTIME_CACHE = ${JSON.stringify(runtimeCache)};
const CURRENT_CACHES = ${currentCaches};
const PRECACHE_URLS = ${precacheUrls};
const BASE_PATH = ${JSON.stringify(basePath)};
const OFFLINE_URL = ${JSON.stringify(p("/offline.html"))};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((name) => !CURRENT_CACHES.includes(name))
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(networkFirstNavigation(request));
    return;
  }

  if (url.pathname.startsWith(BASE_PATH + "/data/v1/")) {
    event.respondWith(cacheFirst(request, DATA_CACHE));
    return;
  }

  if (url.pathname.startsWith(BASE_PATH + "/_next/static/")) {
    event.respondWith(cacheFirst(request, STATIC_CACHE));
    return;
  }

  event.respondWith(staleWhileRevalidate(request, RUNTIME_CACHE));
});

async function networkFirstNavigation(request) {
  try {
    const response = await fetch(request);
    const cache = await caches.open(SHELL_CACHE);
    cache.put(request, response.clone());
    return response;
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    const offline = await caches.match(OFFLINE_URL);
    if (offline) return offline;
    throw err;
  }
}

async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(cacheName);
    cache.put(request, response.clone());
  }
  return response;
}

async function staleWhileRevalidate(request, cacheName) {
  const cached = await caches.match(request);
  const fetchPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        caches.open(cacheName).then((cache) => cache.put(request, response.clone()));
      }
      return response;
    })
    .catch(() => cached);
  return cached || fetchPromise;
}
`;
}

interface WebManifest {
  start_url: string;
  scope?: string;
  icons: { src: string }[];
  shortcuts?: { url: string; icons?: { src: string }[] }[];
  [key: string]: unknown;
}

/**
 * Patches the two static files Next exports byte-for-byte from public/
 * (not touched by Next's own basePath-aware pipeline) so they work under
 * a GitHub Pages project-site subpath.
 */
function patchStaticFilesForBasePath(basePath: string) {
  const manifestPath = join(OUT_DIR, "manifest.webmanifest");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as WebManifest;
  manifest.start_url = `${basePath}/`;
  manifest.scope = `${basePath}/`;
  manifest.icons = manifest.icons.map((icon) => ({ ...icon, src: `${basePath}${icon.src}` }));
  if (manifest.shortcuts) {
    manifest.shortcuts = manifest.shortcuts.map((s) => ({
      ...s,
      url: `${basePath}${s.url}`,
      icons: s.icons?.map((icon) => ({ ...icon, src: `${basePath}${icon.src}` })),
    }));
  }
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");
  console.log(`Patched manifest.webmanifest for base path ${basePath}`);

  const offlinePath = join(OUT_DIR, "offline.html");
  const offlineHtml = readFileSync(offlinePath, "utf8").replace(
    '<a href="/">Back to search</a>',
    `<a href="${basePath}/">Back to search</a>`,
  );
  writeFileSync(offlinePath, offlineHtml, "utf8");
  console.log(`Patched offline.html for base path ${basePath}`);
}

function main() {
  const hash = readDataHash();
  const sw = buildServiceWorker(hash, BASE_PATH);
  writeFileSync(join(OUT_DIR, "sw.js"), sw, "utf8");
  console.log(`Wrote out/sw.js (cache version ${hash}, base path "${BASE_PATH}")`);

  if (BASE_PATH) {
    patchStaticFilesForBasePath(BASE_PATH);
  }
}

main();
