/**
 * The curated topic index: a hand-picked mapping from research topic to the
 * roots/lemmas that cover it, verified against the built corpus
 * (public/data/v1/index.json) at the time this file was written.
 *
 * This is deliberately NOT derived from parsing any tafsir (classical
 * commentary) -- it is a keyword/root index a researcher can use as a
 * starting point, not a claim about what a given school of tafsir
 * considers a verse to be "about". A verse can touch a topic without using
 * any of these roots (metaphor, narrative context, pronouns referring back
 * to an earlier-named subject), and a root can appear without the verse
 * being substantively about the topic (a root's dominant sense isn't
 * always the operative one in a given verse). Every topic page says this
 * plainly; treat this as a fast way to *find candidate verses*, not as a
 * verdict on what a verse means.
 *
 * `src/test/topicDefinitions.test.ts` asserts every root/lemma key
 * referenced here actually exists in the built corpus, so a typo or a
 * future corpus change fails loudly instead of silently resolving to zero
 * verses.
 */

export type TopicSource =
  /** every occurrence of this root, whatever lemma it's classified under */
  | { kind: "root"; root: string }
  /** only the occurrences of one specific lemma within a root shared with unrelated lemmas */
  | { kind: "rootedLemma"; root: string; lemmaKey: string }
  /** a lemma with no root of its own (RootFile.root === null) */
  | { kind: "rootlessLemma"; lemmaKey: string };

export interface TopicDefinition {
  slug: string;
  labelEn: string;
  labelAr: string;
  category:
    | "theme"
    | "prophet"
    | "person"
    | "species"
    | "geography"
    | "geology"
    | "meteorology"
    | "cosmology"
    | "commodities"
    | "object"
    | "book"
    | "angel"
    | "number"
    | "divineName";
  /** One-line explanation of scope and any known ambiguity, shown on the topic page. */
  note?: string;
  sources: TopicSource[];
}

function root(r: string): TopicSource {
  return { kind: "root", root: r };
}
function rootedLemma(r: string, lemmaKey: string): TopicSource {
  return { kind: "rootedLemma", root: r, lemmaKey };
}
function rootlessLemma(lemmaKey: string): TopicSource {
  return { kind: "rootlessLemma", lemmaKey };
}

export const THEME_TOPICS: TopicDefinition[] = [
  {
    slug: "marriage",
    labelEn: "Marriage",
    labelAr: "الزواج",
    category: "theme",
    sources: [root("نكح"), root("زوج")],
  },
  {
    slug: "divorce",
    labelEn: "Divorce",
    labelAr: "الطلاق",
    category: "theme",
    sources: [root("طلق")],
  },
  {
    slug: "trade-and-debt",
    labelEn: "Trade & Debt",
    labelAr: "التجارة والدين",
    category: "theme",
    note: "دين covers both \"debt\" and \"religion\" in this corpus (one root, two senses) -- results include both.",
    sources: [root("تجر"), root("بيع"), root("ربو"), root("دين")],
  },
  {
    slug: "prayer",
    labelEn: "Prayer (Ṣalāh)",
    labelAr: "الصلاة",
    category: "theme",
    sources: [root("صلو"), root("سجد"), root("ركع")],
  },
  {
    slug: "supplication",
    labelEn: "Supplication (Duʿāʾ)",
    labelAr: "الدعاء",
    category: "theme",
    note: "دعو also covers \"to call/summon\" more generally, not only prayerful supplication.",
    sources: [root("دعو")],
  },
  {
    slug: "hajj-and-pilgrimage",
    labelEn: "Ḥajj & Pilgrimage",
    labelAr: "الحج",
    category: "theme",
    note: "عمر (ʿumrah) shares its root with \"age/lifespan\"; filtered to the lemmas عُمْرَة and اعْتَمَرَ so unrelated senses are excluded.",
    sources: [root("حجج"), root("طوف"), rootedLemma("عمر", "عمره"), rootedLemma("عمر", "اعتمر")],
  },
  {
    slug: "fasting",
    labelEn: "Fasting (Ṣawm)",
    labelAr: "الصيام",
    category: "theme",
    sources: [root("صوم")],
  },
  {
    slug: "zakah-and-charity",
    labelEn: "Zakah & Charity",
    labelAr: "الزكاة والصدقة",
    category: "theme",
    note: "صدق also covers \"truth/sincerity\" generally; filtered to the charity-related lemmas (صَدَقَة, تَصَدَّقَ, مُتَصَدِّق, مُتَصَدِّقَة) so the far more common \"truthful/confirming\" senses are excluded.",
    sources: [
      root("زكو"),
      rootedLemma("صدق", "صدقه"),
      rootedLemma("صدق", "تصدق"),
      rootedLemma("صدق", "متصدق"),
      rootedLemma("صدق", "متصدقه"),
      rootedLemma("صدق", "مصدقه"),
    ],
  },
  {
    slug: "inheritance",
    labelEn: "Inheritance",
    labelAr: "الميراث",
    category: "theme",
    sources: [root("ورث")],
  },
  {
    slug: "jihad-and-striving",
    labelEn: "Jihād & Striving",
    labelAr: "الجهاد",
    category: "theme",
    sources: [root("جهد")],
  },
  {
    slug: "knowledge",
    labelEn: "Knowledge",
    labelAr: "العلم",
    category: "theme",
    sources: [root("علم")],
  },
  {
    slug: "patience",
    labelEn: "Patience",
    labelAr: "الصبر",
    category: "theme",
    sources: [root("صبر")],
  },
  {
    slug: "repentance",
    labelEn: "Repentance (Tawbah)",
    labelAr: "التوبة",
    category: "theme",
    sources: [root("توب")],
  },
  {
    slug: "paradise-and-gardens",
    labelEn: "Paradise & Gardens",
    labelAr: "الجنة",
    category: "theme",
    note: "Filtered to the lemma جَنَّة (garden/paradise); a small number of matches are جِنَّة (\"madness\", e.g. 7:184) and جُنَّة (\"shield\"), which share its diacritic-stripped key.",
    sources: [rootedLemma("جنن", "جنه")],
  },
  {
    slug: "jinn",
    labelEn: "Jinn",
    labelAr: "الجن",
    category: "theme",
    note: "Filtered to the lemma جِنّ; excludes جان (which can also mean \"serpent\") and مَجْنُون (\"madman\"), both unrelated senses sharing the same root.",
    sources: [rootedLemma("جنن", "جن")],
  },
  {
    slug: "punishment",
    labelEn: "Punishment & Torment",
    labelAr: "العذاب",
    category: "theme",
    sources: [root("عذب")],
  },
  {
    slug: "creation",
    labelEn: "Creation",
    labelAr: "الخلق",
    category: "theme",
    sources: [root("خلق")],
  },
  {
    slug: "mercy",
    labelEn: "Mercy",
    labelAr: "الرحمة",
    category: "theme",
    sources: [root("رحم")],
  },
  {
    slug: "death",
    labelEn: "Death",
    labelAr: "الموت",
    category: "theme",
    sources: [root("موت")],
  },
  {
    slug: "resurrection",
    labelEn: "Resurrection",
    labelAr: "البعث",
    category: "theme",
    sources: [root("بعث")],
  },
  {
    slug: "disbelief",
    labelEn: "Disbelief (Kufr)",
    labelAr: "الكفر",
    category: "theme",
    sources: [root("كفر")],
  },
  {
    slug: "faith",
    labelEn: "Faith (Īmān)",
    labelAr: "الإيمان",
    category: "theme",
    sources: [root("أمن")],
  },
  {
    slug: "shirk",
    labelEn: "Shirk (Associating Partners)",
    labelAr: "الشرك",
    category: "theme",
    sources: [root("شرك")],
  },
  {
    slug: "guidance-and-misguidance",
    labelEn: "Guidance & Misguidance",
    labelAr: "الهدى والضلال",
    category: "theme",
    sources: [root("هدي"), root("ضلل")],
  },
  {
    slug: "forgiveness",
    labelEn: "Forgiveness",
    labelAr: "المغفرة",
    category: "theme",
    sources: [root("غفر")],
  },
  {
    slug: "justice-and-wrongdoing",
    labelEn: "Justice & Wrongdoing",
    labelAr: "العدل والظلم",
    category: "theme",
    sources: [root("قسط"), root("ظلم")],
  },
  {
    slug: "fear-and-reverence",
    labelEn: "Fear & Reverence",
    labelAr: "الخوف والخشوع",
    category: "theme",
    sources: [root("خوف"), root("خشع")],
  },
  {
    slug: "gratitude",
    labelEn: "Gratitude",
    labelAr: "الشكر",
    category: "theme",
    sources: [root("شكر")],
  },
  {
    slug: "revelation-and-prophecy",
    labelEn: "Revelation & Prophecy",
    labelAr: "الوحي والرسالة",
    category: "theme",
    sources: [root("وحي"), root("نبأ"), root("رسل")],
  },
  {
    slug: "kingship-and-dominion",
    labelEn: "Kingship & Dominion",
    labelAr: "الملك",
    category: "theme",
    sources: [root("ملك")],
  },
  {
    slug: "obligations-and-prohibitions",
    labelEn: "Obligations & Prohibitions",
    labelAr: "الفرائض والمحرمات",
    category: "theme",
    note: "حرم also covers \"sacred/inviolable\" (e.g. the sacred mosque), not only legal prohibition.",
    sources: [root("فرض"), root("حرم")],
  },
  {
    slug: "hellfire",
    labelEn: "Hellfire",
    labelAr: "النار",
    category: "theme",
    sources: [rootedLemma("نور", "نار")],
  },
  {
    slug: "light",
    labelEn: "Light",
    labelAr: "النور",
    category: "theme",
    sources: [rootedLemma("نور", "نور"), rootedLemma("نور", "منير")],
  },
  {
    slug: "signs",
    labelEn: "Signs (Āyāt)",
    labelAr: "الآيات",
    category: "theme",
    sources: [rootedLemma("أيي", "ايه")],
  },
  {
    slug: "this-world",
    labelEn: "This World (Dunyā)",
    labelAr: "الدنيا",
    category: "theme",
    sources: [rootedLemma("دنو", "دنيا")],
  },
  {
    slug: "hypocrisy",
    labelEn: "Hypocrisy (Nifāq)",
    labelAr: "النفاق",
    category: "theme",
    note: "نفق also covers \"spending\" (إنفاق); filtered to the hypocrisy-specific lemmas.",
    sources: [
      rootedLemma("نفق", "منافق"),
      rootedLemma("نفق", "منافقه"),
      rootedLemma("نفق", "نفاق"),
      rootedLemma("نفق", "نافق"),
    ],
  },
  {
    slug: "satan",
    labelEn: "Satan (Shayṭān)",
    labelAr: "الشيطان",
    category: "theme",
    sources: [root("شطن")],
  },
  {
    slug: "the-heart",
    labelEn: "The Heart (Qalb)",
    labelAr: "القلب",
    category: "theme",
    note: "قلب also covers \"to turn/overturn\" (انقلب); filtered to the lemma قَلْب itself.",
    sources: [rootedLemma("قلب", "قلب")],
  },
  {
    slug: "orphans",
    labelEn: "Orphans",
    labelAr: "اليتامى",
    category: "theme",
    sources: [root("يتم")],
  },
  {
    slug: "the-poor-and-needy",
    labelEn: "The Poor & Needy",
    labelAr: "الفقراء والمساكين",
    category: "theme",
    sources: [root("فقر"), rootedLemma("سكن", "مسكين"), rootedLemma("سكن", "مسكنه")],
  },
  {
    slug: "truth-and-falsehood",
    labelEn: "Truth & Falsehood",
    labelAr: "الحق والباطل",
    category: "theme",
    sources: [root("حقق"), root("بطل")],
  },
  {
    slug: "fighting-and-warfare",
    labelEn: "Fighting & Warfare",
    labelAr: "القتال",
    category: "theme",
    sources: [root("قتل")],
  },
  {
    slug: "islam-and-submission",
    labelEn: "Islam & Submission",
    labelAr: "الإسلام",
    category: "theme",
    note: "سلم also covers \"peace/greeting\" (سلام) and other senses; filtered to the submission-to-God lemmas.",
    sources: [rootedLemma("سلم", "مسلم"), rootedLemma("سلم", "اسلم"), rootedLemma("سلم", "اسلام")],
  },
  {
    slug: "peace-and-greetings",
    labelEn: "Peace & Greetings",
    labelAr: "السلام",
    category: "theme",
    sources: [rootedLemma("سلم", "سلام")],
  },
  {
    slug: "reason-and-reflection",
    labelEn: "Reason & Reflection",
    labelAr: "العقل والتفكر",
    category: "theme",
    sources: [root("عقل"), root("فكر")],
  },
  {
    slug: "grief-and-sorrow",
    labelEn: "Grief & Sorrow",
    labelAr: "الحزن",
    category: "theme",
    sources: [root("حزن")],
  },
  {
    slug: "taqwa",
    labelEn: "Taqwa (God-Consciousness)",
    labelAr: "التقوى",
    category: "theme",
    note: "وقي also covers the more general \"to protect/guard\" (وَقَى); most occurrences are the taqwa sense.",
    sources: [root("وقي")],
  },
  {
    slug: "arrogance",
    labelEn: "Arrogance",
    labelAr: "الكبر",
    category: "theme",
    note: "كبر also covers unrelated senses of \"great/greatest\" and \"old age\"; filtered to the arrogance-specific lemmas.",
    sources: [
      rootedLemma("كبر", "استكبر"),
      rootedLemma("كبر", "متكبر"),
      rootedLemma("كبر", "مستكبر"),
      rootedLemma("كبر", "استكبار"),
    ],
  },
  {
    slug: "trust-in-god",
    labelEn: "Trust in God (Tawakkul)",
    labelAr: "التوكل",
    category: "theme",
    sources: [root("وكل")],
  },
];

export const PROPHET_TOPICS: TopicDefinition[] = [
  { slug: "adam", labelEn: "Adam", labelAr: "آدم", category: "prophet", sources: [root("أدم")] },
  { slug: "nuh", labelEn: "Nūḥ (Noah)", labelAr: "نوح", category: "prophet", sources: [rootlessLemma("نوح")] },
  {
    slug: "ibrahim",
    labelEn: "Ibrāhīm (Abraham)",
    labelAr: "إبراهيم",
    category: "prophet",
    sources: [rootlessLemma("ابراهيم")],
  },
  {
    slug: "ismail",
    labelEn: "Ismāʿīl (Ishmael)",
    labelAr: "إسماعيل",
    category: "prophet",
    sources: [rootlessLemma("اسماعيل")],
  },
  {
    slug: "ishaq",
    labelEn: "Isḥāq (Isaac)",
    labelAr: "إسحاق",
    category: "prophet",
    sources: [rootlessLemma("اسحاق")],
  },
  {
    slug: "yaqub",
    labelEn: "Yaʿqūb (Jacob)",
    labelAr: "يعقوب",
    category: "prophet",
    sources: [rootlessLemma("يعقوب")],
  },
  {
    slug: "yusuf",
    labelEn: "Yūsuf (Joseph)",
    labelAr: "يوسف",
    category: "prophet",
    sources: [rootlessLemma("يوسف")],
  },
  { slug: "musa", labelEn: "Mūsā (Moses)", labelAr: "موسى", category: "prophet", sources: [rootlessLemma("موسي")] },
  {
    slug: "harun",
    labelEn: "Hārūn (Aaron)",
    labelAr: "هارون",
    category: "prophet",
    sources: [rootlessLemma("هارون")],
  },
  { slug: "dawud", labelEn: "Dāwūd (David)", labelAr: "داود", category: "prophet", sources: [rootlessLemma("داود")] },
  {
    slug: "sulaiman",
    labelEn: "Sulaymān (Solomon)",
    labelAr: "سليمان",
    category: "prophet",
    sources: [rootlessLemma("سليمان")],
  },
  { slug: "ayyub", labelEn: "Ayyūb (Job)", labelAr: "أيوب", category: "prophet", sources: [rootlessLemma("ايوب")] },
  {
    slug: "yunus",
    labelEn: "Yūnus (Jonah)",
    labelAr: "يونس",
    category: "prophet",
    sources: [rootlessLemma("يونس")],
  },
  { slug: "lut", labelEn: "Lūṭ (Lot)", labelAr: "لوط", category: "prophet", sources: [rootlessLemma("لوط")] },
  {
    slug: "hud",
    labelEn: "Hūd",
    labelAr: "هود",
    category: "prophet",
    note: "The root هود also covers \"to become/be Jewish\" (هاد، يهود) -- filtered here to just the lemma هُود.",
    sources: [rootedLemma("هود", "هود")],
  },
  {
    slug: "salih",
    labelEn: "Ṣāliḥ",
    labelAr: "صالح",
    category: "prophet",
    note: "صالح is also the ordinary adjective \"righteous\"; this corpus doesn't distinguish the two senses, so some matches are the adjective, not the prophet's name.",
    sources: [rootedLemma("صلح", "صالح")],
  },
  {
    slug: "shuaib",
    labelEn: "Shuʿayb",
    labelAr: "شعيب",
    category: "prophet",
    sources: [rootlessLemma("شعيب")],
  },
  {
    slug: "idris",
    labelEn: "Idrīs",
    labelAr: "إدريس",
    category: "prophet",
    sources: [rootlessLemma("ادريس")],
  },
  {
    slug: "ilyas",
    labelEn: "Ilyās (Elijah)",
    labelAr: "إلياس",
    category: "prophet",
    sources: [rootlessLemma("الياس")],
  },
  {
    slug: "al-yasa",
    labelEn: "Al-Yasaʿ (Elisha)",
    labelAr: "اليسع",
    category: "prophet",
    sources: [rootlessLemma("اليسع")],
  },
  {
    slug: "zakariya",
    labelEn: "Zakariyyā (Zechariah)",
    labelAr: "زكريا",
    category: "prophet",
    sources: [rootlessLemma("زكريا")],
  },
  {
    slug: "yahya",
    labelEn: "Yaḥyā (John)",
    labelAr: "يحيى",
    category: "prophet",
    sources: [rootedLemma("حيي", "يحيي")],
  },
  { slug: "isa", labelEn: "ʿĪsā (Jesus)", labelAr: "عيسى", category: "prophet", sources: [rootlessLemma("عيسي")] },
  {
    slug: "muhammad",
    labelEn: "Muḥammad",
    labelAr: "محمد",
    category: "prophet",
    note: "Includes both names the Qur'an uses for him: محمد and أحمد (61:6).",
    sources: [rootedLemma("حمد", "محمد"), rootedLemma("حمد", "احمد")],
  },
];

export const PEOPLE_TOPICS: TopicDefinition[] = [
  {
    slug: "firaun",
    labelEn: "Firʿawn (Pharaoh)",
    labelAr: "فرعون",
    category: "person",
    sources: [rootlessLemma("فرعون")],
  },
  {
    slug: "qarun",
    labelEn: "Qārūn (Korah)",
    labelAr: "قارون",
    category: "person",
    sources: [rootlessLemma("قارون")],
  },
  {
    slug: "luqman",
    labelEn: "Luqmān",
    labelAr: "لقمان",
    category: "person",
    sources: [rootlessLemma("لقمان")],
  },
  {
    slug: "maryam",
    labelEn: "Maryam (Mary)",
    labelAr: "مريم",
    category: "person",
    sources: [rootlessLemma("مريم")],
  },
  {
    slug: "imran",
    labelEn: "ʿImrān",
    labelAr: "عمران",
    category: "person",
    sources: [rootlessLemma("عمران")],
  },
  {
    slug: "talut",
    labelEn: "Ṭālūt (Saul)",
    labelAr: "طالوت",
    category: "person",
    sources: [rootlessLemma("طالوت")],
  },
  {
    slug: "jalut",
    labelEn: "Jālūt (Goliath)",
    labelAr: "جالوت",
    category: "person",
    sources: [rootlessLemma("جالوت")],
  },
  {
    slug: "haman",
    labelEn: "Hāmān",
    labelAr: "هامان",
    category: "person",
    sources: [rootlessLemma("هامان")],
  },
  {
    slug: "iblis",
    labelEn: "Iblīs",
    labelAr: "إبليس",
    category: "person",
    sources: [rootlessLemma("ابليس")],
  },
  {
    slug: "uzayr",
    labelEn: "ʿUzayr (Ezra)",
    labelAr: "عزير",
    category: "person",
    sources: [rootlessLemma("عزير")],
  },
  {
    slug: "al-samiri",
    labelEn: "Al-Sāmirī",
    labelAr: "السامري",
    category: "person",
    note: "السامري shares its root سمر (\"to talk into the night\") with an unrelated word, but the lemma السامري itself is used only for this figure.",
    sources: [rootedLemma("سمر", "سامري")],
  },
  {
    slug: "zayd",
    labelEn: "Zayd (ibn Ḥārithah)",
    labelAr: "زيد",
    category: "person",
    note: "The only one of the Prophet's companions named directly in the Qur'an (33:37).",
    sources: [rootlessLemma("زيد")],
  },
];

export const SPECIES_TOPICS: TopicDefinition[] = [
  {
    slug: "the-cow",
    labelEn: "The Cow",
    labelAr: "البقرة",
    category: "species",
    sources: [root("بقر")],
  },
  {
    slug: "the-camel",
    labelEn: "The Camel",
    labelAr: "الجمل والناقة",
    category: "species",
    note: "جمل's root also covers unrelated senses (\"beautiful\", \"altogether\"); filtered to the lemma جَمَل itself, alongside the separate words ناقة and بعير.",
    sources: [rootedLemma("جمل", "جمل"), root("نوق"), root("بعر")],
  },
  {
    slug: "sheep-and-goats",
    labelEn: "Sheep & Goats",
    labelAr: "الغنم والمعز",
    category: "species",
    note: "غنم's root also covers \"spoils of war\" (مغانم); filtered to the lemma غَنَم itself.",
    sources: [rootedLemma("غنم", "غنم"), root("معز")],
  },
  {
    slug: "donkeys-and-mules",
    labelEn: "Donkeys & Mules",
    labelAr: "الحمير والبغال",
    category: "species",
    note: "حمر's root also covers the color \"red\" (حُمْر); filtered to the lemma حِمار itself.",
    sources: [rootedLemma("حمر", "حمار"), root("بغل")],
  },
  {
    slug: "the-horse",
    labelEn: "The Horse",
    labelAr: "الخيل",
    category: "species",
    note: "خيل's root also covers unrelated senses (\"arrogant\", \"seemed\"); filtered to the lemma خَيْل itself.",
    sources: [rootedLemma("خيل", "خيل")],
  },
  {
    slug: "the-dog",
    labelEn: "The Dog",
    labelAr: "الكلب",
    category: "species",
    sources: [rootedLemma("كلب", "كلب")],
  },
  {
    slug: "the-wolf",
    labelEn: "The Wolf",
    labelAr: "الذئب",
    category: "species",
    sources: [root("ذأب")],
  },
  {
    slug: "the-crow",
    labelEn: "The Crow",
    labelAr: "الغراب",
    category: "species",
    note: "غرب's root also covers \"west/sunset\" (مغرب); filtered to the lemma غُراب itself.",
    sources: [rootedLemma("غرب", "غراب")],
  },
  {
    slug: "snakes-and-serpents",
    labelEn: "Snakes & Serpents",
    labelAr: "الحية والثعبان",
    category: "species",
    note: "حية's root حيي is overwhelmingly about \"life\" (حياة); filtered to just the lemma حَيَّة, alongside the separate word ثعبان.",
    sources: [rootedLemma("حيي", "حيه"), root("ثعب")],
  },
  {
    slug: "monkeys",
    labelEn: "Monkeys",
    labelAr: "القردة",
    category: "species",
    sources: [rootedLemma("قرد", "قرده")],
  },
  {
    slug: "the-pig",
    labelEn: "The Pig",
    labelAr: "الخنزير",
    category: "species",
    sources: [root("خنزر")],
  },
  {
    slug: "the-elephant",
    labelEn: "The Elephant",
    labelAr: "الفيل",
    category: "species",
    sources: [root("فيل")],
  },
  {
    slug: "the-whale",
    labelEn: "The Whale (Jonah's Fish)",
    labelAr: "الحوت",
    category: "species",
    sources: [root("حوت")],
  },
  {
    slug: "the-frog",
    labelEn: "The Frog",
    labelAr: "الضفدع",
    category: "species",
    sources: [rootedLemma("ضفدع", "ضفادع")],
  },
  {
    slug: "the-locust",
    labelEn: "The Locust",
    labelAr: "الجراد",
    category: "species",
    sources: [root("جرد")],
  },
  {
    slug: "lice",
    labelEn: "Lice",
    labelAr: "القمل",
    category: "species",
    sources: [root("قمل")],
  },
  {
    slug: "the-mosquito",
    labelEn: "The Mosquito",
    labelAr: "البعوضة",
    category: "species",
    note: "بعوضة shares its root بعض with the extremely common word \"some/part\", but the lemma بعوضة itself is used only for the insect.",
    sources: [rootedLemma("بعض", "بعوضه")],
  },
  {
    slug: "the-ant",
    labelEn: "The Ant",
    labelAr: "النملة",
    category: "species",
    note: "نمل's root also covers \"fingertips\" (أنامل); filtered to the ant-specific lemmas.",
    sources: [rootedLemma("نمل", "نمل"), rootedLemma("نمل", "نمله")],
  },
  {
    slug: "the-bee",
    labelEn: "The Bee",
    labelAr: "النحلة",
    category: "species",
    note: "نحل's root also covers \"a freely-given gift\" (نِحْلَة, e.g. a dowry); filtered to the lemma نَحْل itself.",
    sources: [rootedLemma("نحل", "نحل")],
  },
  {
    slug: "the-spider",
    labelEn: "The Spider",
    labelAr: "العنكبوت",
    category: "species",
    sources: [root("عنكب")],
  },
  {
    slug: "birds",
    labelEn: "Birds",
    labelAr: "الطير",
    category: "species",
    note: "طير's root also covers \"omen\" (طائر، تطيّر), a distinct classical sense; filtered to the lemma طَيْر itself.",
    sources: [rootedLemma("طير", "طير")],
  },
  {
    slug: "the-hoopoe",
    labelEn: "The Hoopoe",
    labelAr: "الهدهد",
    category: "species",
    sources: [root("هدهد")],
  },
  {
    slug: "the-date-palm",
    labelEn: "The Date Palm",
    labelAr: "النخلة",
    category: "species",
    sources: [root("نخل")],
  },
  {
    slug: "the-grapevine",
    labelEn: "The Grapevine",
    labelAr: "العنب",
    category: "species",
    sources: [root("عنب")],
  },
  {
    slug: "the-pomegranate",
    labelEn: "The Pomegranate",
    labelAr: "الرمان",
    category: "species",
    sources: [root("رمن")],
  },
  {
    slug: "the-fig",
    labelEn: "The Fig",
    labelAr: "التين",
    category: "species",
    sources: [root("تين")],
  },
  {
    slug: "the-olive",
    labelEn: "The Olive",
    labelAr: "الزيتون",
    category: "species",
    sources: [root("زيت")],
  },
  {
    slug: "the-lote-tree",
    labelEn: "The Lote Tree",
    labelAr: "السدرة",
    category: "species",
    sources: [root("سدر")],
  },
  {
    slug: "the-zaqqum-tree",
    labelEn: "The Zaqqūm Tree",
    labelAr: "الزقوم",
    category: "species",
    sources: [root("زقم")],
  },
  {
    slug: "acacia-and-banana-trees",
    labelEn: "Acacia & Banana Trees",
    labelAr: "الطلح",
    category: "species",
    sources: [root("طلح")],
  },
  {
    slug: "the-mustard-seed",
    labelEn: "The Mustard Seed",
    labelAr: "الخردل",
    category: "species",
    sources: [root("خردل")],
  },
];

export const GEOGRAPHY_TOPICS: TopicDefinition[] = [
  {
    slug: "makkah",
    labelEn: "Makkah",
    labelAr: "مكة وبكة",
    category: "geography",
    sources: [rootlessLemma("مكه"), rootlessLemma("بكه")],
  },
  {
    slug: "madinah",
    labelEn: "Al-Madīnah",
    labelAr: "المدينة ويثرب",
    category: "geography",
    note: "مدينة is also the ordinary word for \"a city\" in general, not always the Prophet's city specifically.",
    sources: [rootedLemma("مدن", "مدينه"), rootlessLemma("يثرب")],
  },
  {
    slug: "egypt",
    labelEn: "Egypt (Miṣr)",
    labelAr: "مصر",
    category: "geography",
    sources: [root("مصر")],
  },
  {
    slug: "sheba",
    labelEn: "Sheba (Sabaʾ)",
    labelAr: "سبأ",
    category: "geography",
    sources: [root("سبأ")],
  },
  {
    slug: "babylon",
    labelEn: "Babylon",
    labelAr: "بابل",
    category: "geography",
    sources: [rootlessLemma("بابل")],
  },
  {
    slug: "madyan",
    labelEn: "Madyan (Midian)",
    labelAr: "مدين",
    category: "geography",
    sources: [rootedLemma("مدن", "مدين")],
  },
  {
    slug: "al-ahqaf",
    labelEn: "Al-Aḥqāf",
    labelAr: "الأحقاف",
    category: "geography",
    sources: [root("حقف")],
  },
  {
    slug: "rome",
    labelEn: "Rome (Byzantium)",
    labelAr: "الروم",
    category: "geography",
    sources: [rootlessLemma("روم")],
  },
  {
    slug: "the-thicket",
    labelEn: "The Thicket (Aykah)",
    labelAr: "الأيكة",
    category: "geography",
    sources: [rootlessLemma("ايكه")],
  },
  {
    slug: "tuwa-valley",
    labelEn: "Ṭuwā Valley",
    labelAr: "طوى",
    category: "geography",
    sources: [rootedLemma("طوي", "طوي")],
  },
  {
    slug: "safa-and-marwah",
    labelEn: "Ṣafā & Marwah",
    labelAr: "الصفا والمروة",
    category: "geography",
    sources: [rootlessLemma("صفا"), rootedLemma("مرو", "مروه")],
  },
  {
    slug: "iram",
    labelEn: "Iram",
    labelAr: "إرم",
    category: "geography",
    sources: [rootlessLemma("ارم")],
  },
  {
    slug: "thamud",
    labelEn: "Thamūd",
    labelAr: "ثمود",
    category: "geography",
    sources: [rootlessLemma("ثمود")],
  },
  {
    slug: "quraysh",
    labelEn: "Quraysh",
    labelAr: "قريش",
    category: "geography",
    sources: [rootedLemma("قرش", "قريش")],
  },
  {
    slug: "children-of-israel",
    labelEn: "Children of Israel",
    labelAr: "بنو إسرائيل",
    category: "geography",
    sources: [rootlessLemma("اسرائيل")],
  },
  {
    slug: "gog-and-magog",
    labelEn: "Gog & Magog",
    labelAr: "يأجوج ومأجوج",
    category: "geography",
    sources: [rootlessLemma("ياجوج"), rootlessLemma("ماجوج")],
  },
];

export const GEOLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "mountains",
    labelEn: "Mountains",
    labelAr: "الجبال",
    category: "geology",
    sources: [rootedLemma("جبل", "جبل")],
  },
  {
    slug: "the-sea",
    labelEn: "The Sea",
    labelAr: "البحر",
    category: "geology",
    sources: [rootedLemma("بحر", "بحر")],
  },
  {
    slug: "rivers",
    labelEn: "Rivers",
    labelAr: "الأنهار",
    category: "geology",
    note: "نهر's root also covers \"daytime\" (نَهار), a much more common sense on the same root; filtered to the lemma نَهَر itself.",
    sources: [rootedLemma("نهر", "نهر")],
  },
  {
    slug: "mount-sinai",
    labelEn: "Mount Sinai (Al-Ṭūr)",
    labelAr: "الطور وسيناء",
    category: "geology",
    note: "طور's root also covers \"stages\" (أطوار); filtered to the lemma طُور itself.",
    sources: [rootedLemma("طور", "طور"), rootlessLemma("سيناء")],
  },
  {
    slug: "mount-judi",
    labelEn: "Mount Al-Jūdī",
    labelAr: "الجودي",
    category: "geology",
    sources: [rootedLemma("جود", "جودي")],
  },
  {
    slug: "stones-and-rocks",
    labelEn: "Stones & Rocks",
    labelAr: "الحجارة",
    category: "geology",
    sources: [rootedLemma("حجر", "حجاره")],
  },
];

export const METEOROLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "clouds",
    labelEn: "Clouds",
    labelAr: "السحاب والغمام",
    category: "meteorology",
    note: "Both roots also cover unrelated senses (\"dragged\", \"grief\"); filtered to the cloud-specific lemmas.",
    sources: [rootedLemma("سحب", "سحاب"), rootedLemma("غمم", "غمام")],
  },
  {
    slug: "rain",
    labelEn: "Rain",
    labelAr: "المطر والغيث",
    category: "meteorology",
    sources: [root("مطر"), root("غيث")],
  },
  {
    slug: "wind",
    labelEn: "Wind",
    labelAr: "الريح",
    category: "meteorology",
    note: "ريح's root روح is mostly about \"spirit/soul\" (روح) and other unrelated senses; filtered to the lemma رِيح itself.",
    sources: [rootedLemma("روح", "ريح")],
  },
  {
    slug: "thunder",
    labelEn: "Thunder",
    labelAr: "الرعد",
    category: "meteorology",
    sources: [root("رعد")],
  },
  {
    slug: "lightning",
    labelEn: "Lightning",
    labelAr: "البرق",
    category: "meteorology",
    note: "برق's root also covers \"vessels/goblets\" (أباريق), which is excluded; a small number of matches are the verb \"dazzled\" rather than the noun.",
    sources: [rootedLemma("برق", "برق")],
  },
  {
    slug: "hail",
    labelEn: "Hail",
    labelAr: "البرد",
    category: "meteorology",
    sources: [root("برد")],
  },
];

export const COSMOLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "the-sun",
    labelEn: "The Sun",
    labelAr: "الشمس",
    category: "cosmology",
    sources: [root("شمس")],
  },
  {
    slug: "the-moon",
    labelEn: "The Moon",
    labelAr: "القمر",
    category: "cosmology",
    sources: [root("قمر")],
  },
  {
    slug: "stars",
    labelEn: "Stars",
    labelAr: "النجم",
    category: "cosmology",
    sources: [root("نجم")],
  },
  {
    slug: "constellations",
    labelEn: "Constellations",
    labelAr: "البروج",
    category: "cosmology",
    note: "برج's root also covers \"to display one's adornment ostentatiously\" (تبرّج); filtered to the lemma بُرُوج itself.",
    sources: [rootedLemma("برج", "بروج")],
  },
  {
    slug: "sirius",
    labelEn: "Sirius (Ash-Shiʿrā)",
    labelAr: "الشعرى",
    category: "cosmology",
    note: "شعرى shares its root شعر with \"poetry\", \"hair\" and \"to perceive\"; the lemma شِعْرَى itself is used only for the star.",
    sources: [rootedLemma("شعر", "شعري")],
  },
  {
    slug: "the-sky-and-heavens",
    labelEn: "The Sky & Heavens",
    labelAr: "السماء",
    category: "cosmology",
    note: "سماء's root also covers \"name\" (اسم، سمّى), an unrelated sense; filtered to the lemma سَماء itself.",
    sources: [rootedLemma("سمو", "سماء")],
  },
];

export const COMMODITIES_TOPICS: TopicDefinition[] = [
  {
    slug: "iron",
    labelEn: "Iron",
    labelAr: "الحديد",
    category: "commodities",
    note: "حديد's root also covers \"limits/boundaries\" (حدود), a much more common sense on the same root; filtered to the lemma حَدِيد itself.",
    sources: [rootedLemma("حدد", "حديد")],
  },
  {
    slug: "silver",
    labelEn: "Silver",
    labelAr: "الفضة",
    category: "commodities",
    sources: [rootedLemma("فضض", "فضه")],
  },
  {
    slug: "pearls",
    labelEn: "Pearls",
    labelAr: "اللؤلؤ",
    category: "commodities",
    sources: [root("لؤلؤ")],
  },
  {
    slug: "coral",
    labelEn: "Coral",
    labelAr: "المرجان",
    category: "commodities",
    sources: [rootedLemma("مرج", "مرجان")],
  },
  {
    slug: "brass",
    labelEn: "Brass (Molten Copper)",
    labelAr: "النحاس",
    category: "commodities",
    sources: [rootedLemma("نحس", "نحاس")],
  },
  {
    slug: "silk",
    labelEn: "Silk",
    labelAr: "الحرير",
    category: "commodities",
    sources: [rootedLemma("حرر", "حرير")],
  },
  {
    slug: "musk",
    labelEn: "Musk",
    labelAr: "المسك",
    category: "commodities",
    sources: [rootedLemma("مسك", "مسك")],
  },
];

export const OBJECT_TOPICS: TopicDefinition[] = [
  {
    slug: "ships-and-the-ark",
    labelEn: "Ships & the Ark",
    labelAr: "الفلك والسفينة",
    category: "object",
    note: "فلك's root also covers \"orbit\" (فَلَك, a distinct celestial sense sharing the same diacritic-stripped key); the vast majority of matches are the ship/ark sense.",
    sources: [root("فلك"), root("سفن")],
  },
  {
    slug: "the-kaaba",
    labelEn: "The Kaʿbah",
    labelAr: "الكعبة",
    category: "object",
    sources: [rootedLemma("كعب", "كعبه")],
  },
  {
    slug: "the-balance",
    labelEn: "The Balance (Mīzān)",
    labelAr: "الميزان",
    category: "object",
    sources: [rootedLemma("وزن", "ميزان")],
  },
  {
    slug: "the-pen",
    labelEn: "The Pen",
    labelAr: "القلم",
    category: "object",
    sources: [root("قلم")],
  },
  {
    slug: "the-tablet",
    labelEn: "The Tablet",
    labelAr: "اللوح",
    category: "object",
    note: "لوح's root also covers \"scorching\" (لوّاحة, describing Hellfire); filtered to the lemma لَوْح itself.",
    sources: [rootedLemma("لوح", "لوح")],
  },
  {
    slug: "the-trumpet",
    labelEn: "The Trumpet",
    labelAr: "الصور",
    category: "object",
    note: "صور's root also covers \"formed/shaped\" (صَوَّرَ), which shares the same diacritic-stripped key; most matches are the trumpet.",
    sources: [rootedLemma("صور", "صور")],
  },
  {
    slug: "the-staff",
    labelEn: "The Staff (of Moses)",
    labelAr: "العصا",
    category: "object",
    note: "The same word عصا is tagged under two different root spellings (عصو and عصي) in this corpus; both are included here, filtered away from عصي's unrelated \"disobedience\" senses.",
    sources: [rootedLemma("عصو", "عصا"), rootedLemma("عصي", "عصا")],
  },
  {
    slug: "the-throne",
    labelEn: "The Throne",
    labelAr: "العرش",
    category: "object",
    sources: [rootedLemma("عرش", "عرش")],
  },
  {
    slug: "the-footstool",
    labelEn: "The Footstool (Kursī)",
    labelAr: "الكرسي",
    category: "object",
    sources: [root("كرس")],
  },
  {
    slug: "the-cave",
    labelEn: "The Cave",
    labelAr: "الكهف",
    category: "object",
    sources: [root("كهف")],
  },
];

export const BOOK_TOPICS: TopicDefinition[] = [
  {
    slug: "the-torah",
    labelEn: "The Torah (Tawrāh)",
    labelAr: "التوراة",
    category: "book",
    sources: [rootlessLemma("توراه")],
  },
  {
    slug: "the-gospel",
    labelEn: "The Gospel (Injīl)",
    labelAr: "الإنجيل",
    category: "book",
    sources: [rootlessLemma("انجيل")],
  },
  {
    slug: "the-zabur",
    labelEn: "The Zabūr (Psalms)",
    labelAr: "الزبور",
    category: "book",
    sources: [rootedLemma("زبر", "زبور")],
  },
  {
    slug: "the-scrolls",
    labelEn: "The Scrolls (Ṣuḥuf)",
    labelAr: "الصحف",
    category: "book",
    sources: [rootedLemma("صحف", "صحف")],
  },
  {
    slug: "the-quran",
    labelEn: "The Qurʾān",
    labelAr: "القرآن",
    category: "book",
    sources: [rootedLemma("قرأ", "قرءان")],
  },
  {
    slug: "al-furqan",
    labelEn: "Al-Furqān",
    labelAr: "الفرقان",
    category: "book",
    sources: [rootedLemma("فرق", "فرقان")],
  },
];

export const ANGEL_TOPICS: TopicDefinition[] = [
  {
    slug: "jibril",
    labelEn: "Jibrīl (Gabriel)",
    labelAr: "جبريل",
    category: "angel",
    sources: [rootlessLemma("جبريل")],
  },
  {
    slug: "mikal",
    labelEn: "Mīkāl (Michael)",
    labelAr: "ميكال",
    category: "angel",
    sources: [rootlessLemma("ميكال")],
  },
  {
    slug: "harut-and-marut",
    labelEn: "Hārūt & Mārūt",
    labelAr: "هاروت وماروت",
    category: "angel",
    sources: [rootlessLemma("هاروت"), rootlessLemma("ماروت")],
  },
];

export const NUMBER_TOPICS: TopicDefinition[] = [
  {
    slug: "seven",
    labelEn: "Seven",
    labelAr: "السبع",
    category: "number",
    note: "سبع's root also covers \"beast of prey\" (سَبُع), a small unrelated sense sharing the same diacritic-stripped key.",
    sources: [rootedLemma("سبع", "سبع"), rootedLemma("سبع", "سبعه")],
  },
  {
    slug: "four",
    labelEn: "Four",
    labelAr: "الأربعة",
    category: "number",
    sources: [root("ربع")],
  },
  {
    slug: "eight",
    labelEn: "Eight",
    labelAr: "الثمانية",
    category: "number",
    note: "ثمن's root also covers \"price\" (ثَمَن), its dominant sense; filtered to the eight-specific lemmas.",
    sources: [
      rootedLemma("ثمن", "ثمانيه"),
      rootedLemma("ثمن", "ثامن"),
      rootedLemma("ثمن", "ثماني"),
      rootedLemma("ثمن", "ثمانين"),
    ],
  },
  {
    slug: "ten-and-twenty",
    labelEn: "Ten & Twenty",
    labelAr: "العشرة والعشرون",
    category: "number",
    note: "عشر's root also covers \"a company of people\" (مَعْشَر), which is excluded.",
    sources: [rootedLemma("عشر", "عشر"), rootedLemma("عشر", "عشره"), rootedLemma("عشر", "عشرون")],
  },
  {
    slug: "a-thousand",
    labelEn: "A Thousand",
    labelAr: "الألف",
    category: "number",
    note: "ألف's root also covers \"joined/united [hearts]\" (أَلَّفَ), which shares the same diacritic-stripped key as \"thousand\" and can't be filtered out separately.",
    sources: [rootedLemma("ألف", "الف")],
  },
  {
    slug: "a-hundred",
    labelEn: "A Hundred",
    labelAr: "المائة",
    category: "number",
    sources: [root("مأي")],
  },
];

export const DIVINE_NAME_TOPICS: TopicDefinition[] = [
  {
    slug: "allah",
    labelEn: "Allah",
    labelAr: "الله",
    category: "divineName",
    note: "By far the most frequent word in the Qur'an -- this list is necessarily a representative sample of pages, not something to read end to end.",
    sources: [rootedLemma("أله", "الله")],
  },
  {
    slug: "ar-rahman",
    labelEn: "Ar-Raḥmān (The Most Merciful)",
    labelAr: "الرحمن",
    category: "divineName",
    sources: [rootedLemma("رحم", "رحمن")],
  },
  {
    slug: "ar-raheem",
    labelEn: "Ar-Raḥīm (The Especially Merciful)",
    labelAr: "الرحيم",
    category: "divineName",
    sources: [rootedLemma("رحم", "رحيم")],
  },
  {
    slug: "al-quddus",
    labelEn: "Al-Quddūs (The Most Holy)",
    labelAr: "القدوس",
    category: "divineName",
    sources: [rootedLemma("قدس", "قدوس")],
  },
  {
    slug: "as-samad",
    labelEn: "Aṣ-Ṣamad (The Eternal Refuge)",
    labelAr: "الصمد",
    category: "divineName",
    sources: [root("صمد")],
  },
  {
    slug: "al-wahid",
    labelEn: "Al-Wāḥid (The One)",
    labelAr: "الواحد",
    category: "divineName",
    note: "واحد is also the ordinary word \"one\", not always used as a name for Allah specifically; this corpus doesn't distinguish the two senses.",
    sources: [rootedLemma("وحد", "واحد")],
  },
  {
    slug: "al-qahhar",
    labelEn: "Al-Qahhār (The Subduer)",
    labelAr: "القهار",
    category: "divineName",
    sources: [rootedLemma("قهر", "قهار"), rootedLemma("قهر", "قاهر")],
  },
  {
    slug: "al-hamid",
    labelEn: "Al-Ḥamīd (The Praiseworthy)",
    labelAr: "الحميد",
    category: "divineName",
    sources: [rootedLemma("حمد", "حميد")],
  },
  {
    slug: "al-muhaymin",
    labelEn: "Al-Muhaymin (The Guardian)",
    labelAr: "المهيمن",
    category: "divineName",
    sources: [rootedLemma("همن", "مهيمن")],
  },
  {
    slug: "al-aziz",
    labelEn: "Al-'Azīz (The Almighty)",
    labelAr: "العزيز",
    category: "divineName",
    note: "عزيز also describes powerful people (e.g. Yūsuf's Egyptian master is addressed as \"al-'azīz\" in 12:78), not only Allah.",
    sources: [rootedLemma("عزز", "عزيز")],
  },
  {
    slug: "al-jabbar",
    labelEn: "Al-Jabbār (The Compeller)",
    labelAr: "الجبار",
    category: "divineName",
    note: "جبار describes Allah in only one of its ten occurrences (59:23); the rest describe tyrannical or powerfully-built people (e.g. Pharaoh, the giants of 5:22).",
    sources: [rootedLemma("جبر", "جبار")],
  },
  {
    slug: "al-khaliq",
    labelEn: "Al-Khāliq (The Creator)",
    labelAr: "الخالق",
    category: "divineName",
    sources: [rootedLemma("خلق", "خالق")],
  },
  {
    slug: "al-bari",
    labelEn: "Al-Bāri' (The Maker)",
    labelAr: "البارئ",
    category: "divineName",
    sources: [rootedLemma("برأ", "بارئ")],
  },
  {
    slug: "al-musawwir",
    labelEn: "Al-Muṣawwir (The Fashioner)",
    labelAr: "المصور",
    category: "divineName",
    sources: [rootedLemma("صور", "مصور")],
  },
  {
    slug: "al-ghafur",
    labelEn: "Al-Ghafūr (The All-Forgiving)",
    labelAr: "الغفور",
    category: "divineName",
    sources: [rootedLemma("غفر", "غفور")],
  },
  {
    slug: "al-ghaffar",
    labelEn: "Al-Ghaffār (The Repeatedly Forgiving)",
    labelAr: "الغفار",
    category: "divineName",
    sources: [rootedLemma("غفر", "غفار")],
  },
  {
    slug: "al-ghafir",
    labelEn: "Al-Ghāfir (The Forgiver)",
    labelAr: "الغافر",
    category: "divineName",
    sources: [rootedLemma("غفر", "غافر")],
  },
  {
    slug: "al-fattah",
    labelEn: "Al-Fattāḥ (The Opener)",
    labelAr: "الفتاح",
    category: "divineName",
    sources: [rootedLemma("فتح", "فتاح")],
  },
  {
    slug: "al-alim",
    labelEn: "Al-'Alīm (The All-Knowing)",
    labelAr: "العليم",
    category: "divineName",
    sources: [rootedLemma("علم", "عليم")],
  },
  {
    slug: "al-allam",
    labelEn: "Al-'Allām (The Knower of the Unseen)",
    labelAr: "العلام",
    category: "divineName",
    sources: [rootedLemma("علم", "علام")],
  },
  {
    slug: "al-basit",
    labelEn: "Al-Bāsiṭ (The Extender)",
    labelAr: "الباسط",
    category: "divineName",
    sources: [rootedLemma("بسط", "باسط")],
  },
  {
    slug: "ar-rafi",
    labelEn: "Ar-Rāfi' (The Exalter)",
    labelAr: "الرافع",
    category: "divineName",
    sources: [rootedLemma("رفع", "رافع")],
  },
  {
    slug: "as-sami",
    labelEn: "As-Samī' (The All-Hearing)",
    labelAr: "السميع",
    category: "divineName",
    sources: [rootedLemma("سمع", "سميع")],
  },
  {
    slug: "al-basir",
    labelEn: "Al-Baṣīr (The All-Seeing)",
    labelAr: "البصير",
    category: "divineName",
    sources: [rootedLemma("بصر", "بصير")],
  },
  {
    slug: "al-hakim",
    labelEn: "Al-Ḥakīm (The All-Wise)",
    labelAr: "الحكيم",
    category: "divineName",
    sources: [rootedLemma("حكم", "حكيم")],
  },
  {
    slug: "al-latif",
    labelEn: "Al-Laṭīf (The Subtle One)",
    labelAr: "اللطيف",
    category: "divineName",
    sources: [rootedLemma("لطف", "لطيف")],
  },
  {
    slug: "al-khabir",
    labelEn: "Al-Khabīr (The All-Aware)",
    labelAr: "الخبير",
    category: "divineName",
    sources: [rootedLemma("خبر", "خبير")],
  },
  {
    slug: "al-halim",
    labelEn: "Al-Ḥalīm (The Forbearing)",
    labelAr: "الحليم",
    category: "divineName",
    sources: [rootedLemma("حلم", "حليم")],
  },
  {
    slug: "al-azim",
    labelEn: "Al-'Aẓīm (The Magnificent)",
    labelAr: "العظيم",
    category: "divineName",
    sources: [rootedLemma("عظم", "عظيم")],
  },
  {
    slug: "ash-shakur",
    labelEn: "Ash-Shakūr (The Most Appreciative)",
    labelAr: "الشكور",
    category: "divineName",
    sources: [rootedLemma("شكر", "شكور")],
  },
  {
    slug: "al-aliyy",
    labelEn: "Al-'Aliyy (The Most High)",
    labelAr: "العلي",
    category: "divineName",
    note: "The same stripped key also covers عِلِّيّون, the highest register of the record of the righteous (83:18-19) -- a related but distinct usage.",
    sources: [rootedLemma("علو", "علي")],
  },
  {
    slug: "al-mutaali",
    labelEn: "Al-Muta'āli (The Supreme)",
    labelAr: "المتعالي",
    category: "divineName",
    sources: [rootedLemma("علو", "متعال")],
  },
  {
    slug: "al-hafiz",
    labelEn: "Al-Ḥafīẓ (The Preserver)",
    labelAr: "الحفيظ",
    category: "divineName",
    sources: [rootedLemma("حفظ", "حفيظ")],
  },
  {
    slug: "al-muqit",
    labelEn: "Al-Muqīt (The Sustainer)",
    labelAr: "المقيت",
    category: "divineName",
    sources: [rootedLemma("قوت", "مقيت")],
  },
  {
    slug: "al-hasib",
    labelEn: "Al-Ḥasīb (The Reckoner)",
    labelAr: "الحسيب",
    category: "divineName",
    sources: [rootedLemma("حسب", "حسيب")],
  },
  {
    slug: "dhul-jalal-wal-ikram",
    labelEn: "Dhū al-Jalāl (Possessor of Majesty)",
    labelAr: "ذو الجلال",
    category: "divineName",
    note: "Only attested as part of the fuller phrase \"ذُو الْجَلَالِ وَالْإِكْرَامِ\" (Possessor of Majesty and Honor), in 55:27 and 55:78.",
    sources: [rootedLemma("جلل", "جلال")],
  },
  {
    slug: "al-karim",
    labelEn: "Al-Karīm (The Most Generous)",
    labelAr: "الكريم",
    category: "divineName",
    note: "كريم also describes other things as \"noble\" (the Qur'an, the Throne, a messenger), not only Allah.",
    sources: [rootedLemma("كرم", "كريم")],
  },
  {
    slug: "ar-raqib",
    labelEn: "Ar-Raqīb (The Watchful)",
    labelAr: "الرقيب",
    category: "divineName",
    sources: [rootedLemma("رقب", "رقيب")],
  },
  {
    slug: "al-mujib",
    labelEn: "Al-Mujīb (The Responsive)",
    labelAr: "المجيب",
    category: "divineName",
    sources: [rootedLemma("جوب", "مجيب")],
  },
  {
    slug: "al-wasi",
    labelEn: "Al-Wāsi' (The All-Encompassing)",
    labelAr: "الواسع",
    category: "divineName",
    sources: [rootedLemma("وسع", "واسع")],
  },
  {
    slug: "al-wadud",
    labelEn: "Al-Wadūd (The Most Loving)",
    labelAr: "الودود",
    category: "divineName",
    sources: [rootedLemma("ودد", "ودود")],
  },
  {
    slug: "al-majid",
    labelEn: "Al-Majīd (The Most Glorious)",
    labelAr: "المجيد",
    category: "divineName",
    sources: [rootedLemma("مجد", "مجيد")],
  },
  {
    slug: "ash-shahid",
    labelEn: "Ash-Shahīd (The Witness)",
    labelAr: "الشهيد",
    category: "divineName",
    note: "شهيد also describes human witnesses and martyrs, not only Allah.",
    sources: [rootedLemma("شهد", "شهيد")],
  },
  {
    slug: "al-wakil",
    labelEn: "Al-Wakīl (The Trustee)",
    labelAr: "الوكيل",
    category: "divineName",
    sources: [rootedLemma("وكل", "وكيل")],
  },
  {
    slug: "al-qawiyy",
    labelEn: "Al-Qawiyy (The All-Strong)",
    labelAr: "القوي",
    category: "divineName",
    note: "قوي also describes strong people (e.g. 28:26), not only Allah.",
    sources: [rootedLemma("قوي", "قوي")],
  },
  {
    slug: "al-matin",
    labelEn: "Al-Matīn (The Firm)",
    labelAr: "المتين",
    category: "divineName",
    sources: [rootedLemma("متن", "متين")],
  },
  {
    slug: "al-qayyum",
    labelEn: "Al-Qayyūm (The Self-Subsisting)",
    labelAr: "القيوم",
    category: "divineName",
    sources: [rootedLemma("قوم", "قيوم")],
  },
  {
    slug: "al-qadir",
    labelEn: "Al-Qadīr (The All-Powerful)",
    labelAr: "القدير / القادر",
    category: "divineName",
    sources: [rootedLemma("قدر", "قدير"), rootedLemma("قدر", "قادر")],
  },
  {
    slug: "al-muqtadir",
    labelEn: "Al-Muqtadir (The Determiner)",
    labelAr: "المقتدر",
    category: "divineName",
    sources: [rootedLemma("قدر", "مقتدر")],
  },
  {
    slug: "al-batin",
    labelEn: "Al-Bāṭin (The Hidden)",
    labelAr: "الباطن",
    category: "divineName",
    sources: [rootedLemma("بطن", "باطن")],
  },
  {
    slug: "at-tawwab",
    labelEn: "At-Tawwāb (The Ever-Accepting of Repentance)",
    labelAr: "التواب",
    category: "divineName",
    sources: [rootedLemma("توب", "تواب")],
  },
  {
    slug: "al-muntaqim",
    labelEn: "Al-Muntaqim (The Avenger)",
    labelAr: "المنتقم",
    category: "divineName",
    sources: [rootedLemma("نقم", "منتقم")],
  },
  {
    slug: "al-afuww",
    labelEn: "Al-'Afuww (The Pardoner)",
    labelAr: "العفو",
    category: "divineName",
    note: "The same stripped key also covers عَفْو, the ordinary noun \"pardon\" -- about 2 of these 7 occurrences are the noun rather than the name.",
    sources: [rootedLemma("عفو", "عفو")],
  },
  {
    slug: "ar-rauf",
    labelEn: "Ar-Ra'ūf (The Most Kind)",
    labelAr: "الرؤوف",
    category: "divineName",
    sources: [rootedLemma("رأف", "رءوف")],
  },
  {
    slug: "al-muqsit",
    labelEn: "Al-Muqsiṭ (The Equitable)",
    labelAr: "المقسط",
    category: "divineName",
    sources: [rootedLemma("قسط", "مقسط")],
  },
  {
    slug: "al-jami",
    labelEn: "Al-Jāmi' (The Gatherer)",
    labelAr: "الجامع",
    category: "divineName",
    sources: [rootedLemma("جمع", "جامع")],
  },
  {
    slug: "al-ghani",
    labelEn: "Al-Ghanī (The Self-Sufficient)",
    labelAr: "الغني",
    category: "divineName",
    sources: [rootedLemma("غني", "غني")],
  },
  {
    slug: "al-mughni",
    labelEn: "Al-Mughnī (The Enricher)",
    labelAr: "المغني",
    category: "divineName",
    sources: [rootedLemma("غني", "مغني")],
  },
  {
    slug: "al-badi",
    labelEn: "Al-Badī' (The Originator)",
    labelAr: "البديع",
    category: "divineName",
    sources: [rootedLemma("بدع", "بديع")],
  },
  {
    slug: "al-baqi",
    labelEn: "Al-Bāqī (The Everlasting)",
    labelAr: "الباقي",
    category: "divineName",
    sources: [rootedLemma("بقي", "باقي"), rootedLemma("بقي", "باق")],
  },
  {
    slug: "al-warith",
    labelEn: "Al-Wārith (The Inheritor)",
    labelAr: "الوارث",
    category: "divineName",
    sources: [rootedLemma("ورث", "وارث")],
  },
  {
    slug: "al-waliyy",
    labelEn: "Al-Waliyy (The Protecting Friend)",
    labelAr: "الولي",
    category: "divineName",
    note: "The same stripped key also covers وَلَّى (\"turned away\"), an unrelated verb -- roughly a quarter of these occurrences are that verb, not the name.",
    sources: [rootedLemma("ولي", "ولي")],
  },
  {
    slug: "al-malik",
    labelEn: "Al-Malik (The King)",
    labelAr: "الملك / مالك",
    category: "divineName",
    note: "The common spelling مَلِك shares its stripped key with the unrelated مَلَك (angel), مُلْك (dominion) and مَلَكَتْ (possessed), and can't be isolated from them; this uses the two clean alternate forms مَلِيك and مَالِك instead, the latter also the reading of \"Master of the Day of Judgment\" in the Fātiḥa (1:4).",
    sources: [rootedLemma("ملك", "مليك"), rootedLemma("ملك", "مالك")],
  },
  {
    slug: "al-ahad",
    labelEn: "Al-Aḥad (The One)",
    labelAr: "الأحد",
    category: "divineName",
    note: "أحد is far more often the ordinary indefinite pronoun \"anyone/no one\" than the divine name; this corpus doesn't distinguish the two senses, so most matches are the pronoun.",
    sources: [rootedLemma("أحد", "احد")],
  },
  {
    slug: "al-awwal",
    labelEn: "Al-Awwal (The First)",
    labelAr: "الأول",
    category: "divineName",
    note: "أول is also the ordinary adjective \"first\", not always used as a name for Allah specifically; this corpus doesn't distinguish the two senses.",
    sources: [rootedLemma("أول", "اول")],
  },
];

export const ALL_TOPICS: TopicDefinition[] = [
  ...THEME_TOPICS,
  ...PROPHET_TOPICS,
  ...PEOPLE_TOPICS,
  ...SPECIES_TOPICS,
  ...GEOGRAPHY_TOPICS,
  ...GEOLOGY_TOPICS,
  ...METEOROLOGY_TOPICS,
  ...COSMOLOGY_TOPICS,
  ...COMMODITIES_TOPICS,
  ...OBJECT_TOPICS,
  ...BOOK_TOPICS,
  ...ANGEL_TOPICS,
  ...NUMBER_TOPICS,
  ...DIVINE_NAME_TOPICS,
];

export function findTopicBySlug(slug: string): TopicDefinition | undefined {
  return ALL_TOPICS.find((t) => t.slug === slug);
}
