/**
 * The curated topic index: a hand-picked mapping from research topic to the
 * roots/lemmas that cover it, verified against the built corpus
 * (public/data/v1/index.json) at the time this file was written.
 *
 * This is deliberately NOT derived from parsing any tafsir (classical
 * commentary) -- it is a keyword/root index a researcher can use as a
 * starting point, not a claim about what a given school of tafsir
 * considers a verse to be "about". A verse can touch a topic without using
 * any of these roots (metaphor, narrative context, pronouns referring back
 * to an earlier-named subject), and a root can appear without the verse
 * being substantively about the topic (a root's dominant sense isn't
 * always the operative one in a given verse). Every topic page says this
 * plainly; treat this as a fast way to *find candidate verses*, not as a
 * verdict on what a verse means.
 *
 * `src/test/topicDefinitions.test.ts` asserts every root/lemma key
 * referenced here actually exists in the built corpus, so a typo or a
 * future corpus change fails loudly instead of silently resolving to zero
 * verses.
 */

export type TopicSource =
  /** every occurrence of this root, whatever lemma it's classified under */
  | { kind: "root"; root: string }
  /** only the occurrences of one specific lemma within a root shared with unrelated lemmas */
  | { kind: "rootedLemma"; root: string; lemmaKey: string }
  /** a lemma with no root of its own (RootFile.root === null) */
  | { kind: "rootlessLemma"; lemmaKey: string };

export interface TopicDefinition {
  slug: string;
  labelEn: string;
  labelAr: string;
  category: "theme" | "prophet" | "person" | "species" | "geography" | "geology" | "meteorology" | "cosmology" | "commodities";
  /** One-line explanation of scope and any known ambiguity, shown on the topic page. */
  note?: string;
  sources: TopicSource[];
}

function root(r: string): TopicSource {
  return { kind: "root", root: r };
}
function rootedLemma(r: string, lemmaKey: string): TopicSource {
  return { kind: "rootedLemma", root: r, lemmaKey };
}
function rootlessLemma(lemmaKey: string): TopicSource {
  return { kind: "rootlessLemma", lemmaKey };
}

export const THEME_TOPICS: TopicDefinition[] = [
  {
    slug: "marriage",
    labelEn: "Marriage",
    labelAr: "الزواج",
    category: "theme",
    sources: [root("نكح"), root("زوج")],
  },
  {
    slug: "divorce",
    labelEn: "Divorce",
    labelAr: "الطلاق",
    category: "theme",
    sources: [root("طلق")],
  },
  {
    slug: "trade-and-debt",
    labelEn: "Trade & Debt",
    labelAr: "التجارة والدين",
    category: "theme",
    note: "دين covers both \"debt\" and \"religion\" in this corpus (one root, two senses) -- results include both.",
    sources: [root("تجر"), root("بيع"), root("ربو"), root("دين")],
  },
  {
    slug: "prayer",
    labelEn: "Prayer (Ṣalāh)",
    labelAr: "الصلاة",
    category: "theme",
    sources: [root("صلو"), root("سجد"), root("ركع")],
  },
  {
    slug: "supplication",
    labelEn: "Supplication (Duʿāʾ)",
    labelAr: "الدعاء",
    category: "theme",
    note: "دعو also covers \"to call/summon\" more generally, not only prayerful supplication.",
    sources: [root("دعو")],
  },
  {
    slug: "hajj-and-pilgrimage",
    labelEn: "Ḥajj & Pilgrimage",
    labelAr: "الحج",
    category: "theme",
    note: "عمر (ʿumrah) shares its root with \"age/lifespan\"; filtered to the lemmas عُمْرَة and اعْتَمَرَ so unrelated senses are excluded.",
    sources: [root("حجج"), root("طوف"), rootedLemma("عمر", "عمره"), rootedLemma("عمر", "اعتمر")],
  },
  {
    slug: "fasting",
    labelEn: "Fasting (Ṣawm)",
    labelAr: "الصيام",
    category: "theme",
    sources: [root("صوم")],
  },
  {
    slug: "zakah-and-charity",
    labelEn: "Zakah & Charity",
    labelAr: "الزكاة والصدقة",
    category: "theme",
    note: "صدق also covers \"truth/sincerity\" generally; filtered to the charity-related lemmas (صَدَقَة, تَصَدَّقَ, مُتَصَدِّق, مُتَصَدِّقَة) so the far more common \"truthful/confirming\" senses are excluded.",
    sources: [
      root("زكو"),
      rootedLemma("صدق", "صدقه"),
      rootedLemma("صدق", "تصدق"),
      rootedLemma("صدق", "متصدق"),
      rootedLemma("صدق", "متصدقه"),
      rootedLemma("صدق", "مصدقه"),
    ],
  },
  {
    slug: "inheritance",
    labelEn: "Inheritance",
    labelAr: "الميراث",
    category: "theme",
    sources: [root("ورث")],
  },
  {
    slug: "jihad-and-striving",
    labelEn: "Jihād & Striving",
    labelAr: "الجهاد",
    category: "theme",
    sources: [root("جهد")],
  },
  {
    slug: "knowledge",
    labelEn: "Knowledge",
    labelAr: "العلم",
    category: "theme",
    sources: [root("علم")],
  },
  {
    slug: "patience",
    labelEn: "Patience",
    labelAr: "الصبر",
    category: "theme",
    sources: [root("صبر")],
  },
  {
    slug: "repentance",
    labelEn: "Repentance (Tawbah)",
    labelAr: "التوبة",
    category: "theme",
    sources: [root("توب")],
  },
  {
    slug: "paradise-and-gardens",
    labelEn: "Paradise & Gardens",
    labelAr: "الجنة",
    category: "theme",
    note: "Filtered to the lemma جَنَّة (garden/paradise); a small number of matches are جِنَّة (\"madness\", e.g. 7:184) and جُنَّة (\"shield\"), which share its diacritic-stripped key.",
    sources: [rootedLemma("جنن", "جنه")],
  },
  {
    slug: "jinn",
    labelEn: "Jinn",
    labelAr: "الجن",
    category: "theme",
    note: "Filtered to the lemma جِنّ; excludes جان (which can also mean \"serpent\") and مَجْنُون (\"madman\"), both unrelated senses sharing the same root.",
    sources: [rootedLemma("جنن", "جن")],
  },
  {
    slug: "punishment",
    labelEn: "Punishment & Torment",
    labelAr: "العذاب",
    category: "theme",
    sources: [root("عذب")],
  },
  {
    slug: "creation",
    labelEn: "Creation",
    labelAr: "الخلق",
    category: "theme",
    sources: [root("خلق")],
  },
  {
    slug: "mercy",
    labelEn: "Mercy",
    labelAr: "الرحمة",
    category: "theme",
    sources: [root("رحم")],
  },
  {
    slug: "death",
    labelEn: "Death",
    labelAr: "الموت",
    category: "theme",
    sources: [root("موت")],
  },
  {
    slug: "resurrection",
    labelEn: "Resurrection",
    labelAr: "البعث",
    category: "theme",
    sources: [root("بعث")],
  },
  {
    slug: "disbelief",
    labelEn: "Disbelief (Kufr)",
    labelAr: "الكفر",
    category: "theme",
    sources: [root("كفر")],
  },
  {
    slug: "faith",
    labelEn: "Faith (Īmān)",
    labelAr: "الإيمان",
    category: "theme",
    sources: [root("أمن")],
  },
  {
    slug: "shirk",
    labelEn: "Shirk (Associating Partners)",
    labelAr: "الشرك",
    category: "theme",
    sources: [root("شرك")],
  },
  {
    slug: "guidance-and-misguidance",
    labelEn: "Guidance & Misguidance",
    labelAr: "الهدى والضلال",
    category: "theme",
    sources: [root("هدي"), root("ضلل")],
  },
  {
    slug: "forgiveness",
    labelEn: "Forgiveness",
    labelAr: "المغفرة",
    category: "theme",
    sources: [root("غفر")],
  },
  {
    slug: "justice-and-wrongdoing",
    labelEn: "Justice & Wrongdoing",
    labelAr: "العدل والظلم",
    category: "theme",
    sources: [root("قسط"), root("ظلم")],
  },
  {
    slug: "fear-and-reverence",
    labelEn: "Fear & Reverence",
    labelAr: "الخوف والخشوع",
    category: "theme",
    sources: [root("خوف"), root("خشع")],
  },
  {
    slug: "gratitude",
    labelEn: "Gratitude",
    labelAr: "الشكر",
    category: "theme",
    sources: [root("شكر")],
  },
  {
    slug: "revelation-and-prophecy",
    labelEn: "Revelation & Prophecy",
    labelAr: "الوحي والرسالة",
    category: "theme",
    sources: [root("وحي"), root("نبأ"), root("رسل")],
  },
  {
    slug: "kingship-and-dominion",
    labelEn: "Kingship & Dominion",
    labelAr: "الملك",
    category: "theme",
    sources: [root("ملك")],
  },
  {
    slug: "obligations-and-prohibitions",
    labelEn: "Obligations & Prohibitions",
    labelAr: "الفرائض والمحرمات",
    category: "theme",
    note: "حرم also covers \"sacred/inviolable\" (e.g. the sacred mosque), not only legal prohibition.",
    sources: [root("فرض"), root("حرم")],
  },
  {
    slug: "hellfire",
    labelEn: "Hellfire",
    labelAr: "النار",
    category: "theme",
    sources: [rootedLemma("نور", "نار")],
  },
  {
    slug: "light",
    labelEn: "Light",
    labelAr: "النور",
    category: "theme",
    sources: [rootedLemma("نور", "نور"), rootedLemma("نور", "منير")],
  },
  {
    slug: "signs",
    labelEn: "Signs (Āyāt)",
    labelAr: "الآيات",
    category: "theme",
    sources: [rootedLemma("أيي", "ايه")],
  },
  {
    slug: "this-world",
    labelEn: "This World (Dunyā)",
    labelAr: "الدنيا",
    category: "theme",
    sources: [rootedLemma("دنو", "دنيا")],
  },
  {
    slug: "hypocrisy",
    labelEn: "Hypocrisy (Nifāq)",
    labelAr: "النفاق",
    category: "theme",
    note: "نفق also covers \"spending\" (إنفاق); filtered to the hypocrisy-specific lemmas.",
    sources: [
      rootedLemma("نفق", "منافق"),
      rootedLemma("نفق", "منافقه"),
      rootedLemma("نفق", "نفاق"),
      rootedLemma("نفق", "نافق"),
    ],
  },
  {
    slug: "satan",
    labelEn: "Satan (Shayṭān)",
    labelAr: "الشيطان",
    category: "theme",
    sources: [root("شطن")],
  },
  {
    slug: "the-heart",
    labelEn: "The Heart (Qalb)",
    labelAr: "القلب",
    category: "theme",
    note: "قلب also covers \"to turn/overturn\" (انقلب); filtered to the lemma قَلْب itself.",
    sources: [rootedLemma("قلب", "قلب")],
  },
  {
    slug: "orphans",
    labelEn: "Orphans",
    labelAr: "اليتامى",
    category: "theme",
    sources: [root("يتم")],
  },
  {
    slug: "the-poor-and-needy",
    labelEn: "The Poor & Needy",
    labelAr: "الفقراء والمساكين",
    category: "theme",
    sources: [root("فقر"), rootedLemma("سكن", "مسكين"), rootedLemma("سكن", "مسكنه")],
  },
  {
    slug: "truth-and-falsehood",
    labelEn: "Truth & Falsehood",
    labelAr: "الحق والباطل",
    category: "theme",
    sources: [root("حقق"), root("بطل")],
  },
  {
    slug: "fighting-and-warfare",
    labelEn: "Fighting & Warfare",
    labelAr: "القتال",
    category: "theme",
    sources: [root("قتل")],
  },
  {
    slug: "islam-and-submission",
    labelEn: "Islam & Submission",
    labelAr: "الإسلام",
    category: "theme",
    note: "سلم also covers \"peace/greeting\" (سلام) and other senses; filtered to the submission-to-God lemmas.",
    sources: [rootedLemma("سلم", "مسلم"), rootedLemma("سلم", "اسلم"), rootedLemma("سلم", "اسلام")],
  },
  {
    slug: "peace-and-greetings",
    labelEn: "Peace & Greetings",
    labelAr: "السلام",
    category: "theme",
    sources: [rootedLemma("سلم", "سلام")],
  },
  {
    slug: "reason-and-reflection",
    labelEn: "Reason & Reflection",
    labelAr: "العقل والتفكر",
    category: "theme",
    sources: [root("عقل"), root("فكر")],
  },
  {
    slug: "grief-and-sorrow",
    labelEn: "Grief & Sorrow",
    labelAr: "الحزن",
    category: "theme",
    sources: [root("حزن")],
  },
  {
    slug: "taqwa",
    labelEn: "Taqwa (God-Consciousness)",
    labelAr: "التقوى",
    category: "theme",
    note: "وقي also covers the more general \"to protect/guard\" (وَقَى); most occurrences are the taqwa sense.",
    sources: [root("وقي")],
  },
  {
    slug: "arrogance",
    labelEn: "Arrogance",
    labelAr: "الكبر",
    category: "theme",
    note: "كبر also covers unrelated senses of \"great/greatest\" and \"old age\"; filtered to the arrogance-specific lemmas.",
    sources: [
      rootedLemma("كبر", "استكبر"),
      rootedLemma("كبر", "متكبر"),
      rootedLemma("كبر", "مستكبر"),
      rootedLemma("كبر", "استكبار"),
    ],
  },
  {
    slug: "trust-in-god",
    labelEn: "Trust in God (Tawakkul)",
    labelAr: "التوكل",
    category: "theme",
    sources: [root("وكل")],
  },
];

export const PROPHET_TOPICS: TopicDefinition[] = [
  { slug: "adam", labelEn: "Adam", labelAr: "آدم", category: "prophet", sources: [root("أدم")] },
  { slug: "nuh", labelEn: "Nūḥ (Noah)", labelAr: "نوح", category: "prophet", sources: [rootlessLemma("نوح")] },
  {
    slug: "ibrahim",
    labelEn: "Ibrāhīm (Abraham)",
    labelAr: "إبراهيم",
    category: "prophet",
    sources: [rootlessLemma("ابراهيم")],
  },
  {
    slug: "ismail",
    labelEn: "Ismāʿīl (Ishmael)",
    labelAr: "إسماعيل",
    category: "prophet",
    sources: [rootlessLemma("اسماعيل")],
  },
  {
    slug: "ishaq",
    labelEn: "Isḥāq (Isaac)",
    labelAr: "إسحاق",
    category: "prophet",
    sources: [rootlessLemma("اسحاق")],
  },
  {
    slug: "yaqub",
    labelEn: "Yaʿqūb (Jacob)",
    labelAr: "يعقوب",
    category: "prophet",
    sources: [rootlessLemma("يعقوب")],
  },
  {
    slug: "yusuf",
    labelEn: "Yūsuf (Joseph)",
    labelAr: "يوسف",
    category: "prophet",
    sources: [rootlessLemma("يوسف")],
  },
  { slug: "musa", labelEn: "Mūsā (Moses)", labelAr: "موسى", category: "prophet", sources: [rootlessLemma("موسي")] },
  {
    slug: "harun",
    labelEn: "Hārūn (Aaron)",
    labelAr: "هارون",
    category: "prophet",
    sources: [rootlessLemma("هارون")],
  },
  { slug: "dawud", labelEn: "Dāwūd (David)", labelAr: "داود", category: "prophet", sources: [rootlessLemma("داود")] },
  {
    slug: "sulaiman",
    labelEn: "Sulaymān (Solomon)",
    labelAr: "سليمان",
    category: "prophet",
    sources: [rootlessLemma("سليمان")],
  },
  { slug: "ayyub", labelEn: "Ayyūb (Job)", labelAr: "أيوب", category: "prophet", sources: [rootlessLemma("ايوب")] },
  {
    slug: "yunus",
    labelEn: "Yūnus (Jonah)",
    labelAr: "يونس",
    category: "prophet",
    sources: [rootlessLemma("يونس")],
  },
  { slug: "lut", labelEn: "Lūṭ (Lot)", labelAr: "لوط", category: "prophet", sources: [rootlessLemma("لوط")] },
  {
    slug: "hud",
    labelEn: "Hūd",
    labelAr: "هود",
    category: "prophet",
    note: "The root هود also covers \"to become/be Jewish\" (هاد، يهود) -- filtered here to just the lemma هُود.",
    sources: [rootedLemma("هود", "هود")],
  },
  {
    slug: "salih",
    labelEn: "Ṣāliḥ",
    labelAr: "صالح",
    category: "prophet",
    note: "صالح is also the ordinary adjective \"righteous\"; this corpus doesn't distinguish the two senses, so some matches are the adjective, not the prophet's name.",
    sources: [rootedLemma("صلح", "صالح")],
  },
  {
    slug: "shuaib",
    labelEn: "Shuʿayb",
    labelAr: "شعيب",
    category: "prophet",
    sources: [rootlessLemma("شعيب")],
  },
  {
    slug: "idris",
    labelEn: "Idrīs",
    labelAr: "إدريس",
    category: "prophet",
    sources: [rootlessLemma("ادريس")],
  },
  {
    slug: "ilyas",
    labelEn: "Ilyās (Elijah)",
    labelAr: "إلياس",
    category: "prophet",
    sources: [rootlessLemma("الياس")],
  },
  {
    slug: "al-yasa",
    labelEn: "Al-Yasaʿ (Elisha)",
    labelAr: "اليسع",
    category: "prophet",
    sources: [rootlessLemma("اليسع")],
  },
  {
    slug: "zakariya",
    labelEn: "Zakariyyā (Zechariah)",
    labelAr: "زكريا",
    category: "prophet",
    sources: [rootlessLemma("زكريا")],
  },
  {
    slug: "yahya",
    labelEn: "Yaḥyā (John)",
    labelAr: "يحيى",
    category: "prophet",
    sources: [rootedLemma("حيي", "يحيي")],
  },
  { slug: "isa", labelEn: "ʿĪsā (Jesus)", labelAr: "عيسى", category: "prophet", sources: [rootlessLemma("عيسي")] },
  {
    slug: "muhammad",
    labelEn: "Muḥammad",
    labelAr: "محمد",
    category: "prophet",
    note: "Includes both names the Qur'an uses for him: محمد and أحمد (61:6).",
    sources: [rootedLemma("حمد", "محمد"), rootedLemma("حمد", "احمد")],
  },
];

export const PEOPLE_TOPICS: TopicDefinition[] = [
  {
    slug: "firaun",
    labelEn: "Firʿawn (Pharaoh)",
    labelAr: "فرعون",
    category: "person",
    sources: [rootlessLemma("فرعون")],
  },
  {
    slug: "qarun",
    labelEn: "Qārūn (Korah)",
    labelAr: "قارون",
    category: "person",
    sources: [rootlessLemma("قارون")],
  },
  {
    slug: "luqman",
    labelEn: "Luqmān",
    labelAr: "لقمان",
    category: "person",
    sources: [rootlessLemma("لقمان")],
  },
  {
    slug: "maryam",
    labelEn: "Maryam (Mary)",
    labelAr: "مريم",
    category: "person",
    sources: [rootlessLemma("مريم")],
  },
  {
    slug: "imran",
    labelEn: "ʿImrān",
    labelAr: "عمران",
    category: "person",
    sources: [rootlessLemma("عمران")],
  },
  {
    slug: "talut",
    labelEn: "Ṭālūt (Saul)",
    labelAr: "طالوت",
    category: "person",
    sources: [rootlessLemma("طالوت")],
  },
  {
    slug: "jalut",
    labelEn: "Jālūt (Goliath)",
    labelAr: "جالوت",
    category: "person",
    sources: [rootlessLemma("جالوت")],
  },
  {
    slug: "haman",
    labelEn: "Hāmān",
    labelAr: "هامان",
    category: "person",
    sources: [rootlessLemma("هامان")],
  },
  {
    slug: "iblis",
    labelEn: "Iblīs",
    labelAr: "إبليس",
    category: "person",
    sources: [rootlessLemma("ابليس")],
  },
  {
    slug: "uzayr",
    labelEn: "ʿUzayr (Ezra)",
    labelAr: "عزير",
    category: "person",
    sources: [rootlessLemma("عزير")],
  },
  {
    slug: "al-samiri",
    labelEn: "Al-Sāmirī",
    labelAr: "السامري",
    category: "person",
    note: "السامري shares its root سمر (\"to talk into the night\") with an unrelated word, but the lemma السامري itself is used only for this figure.",
    sources: [rootedLemma("سمر", "سامري")],
  },
  {
    slug: "zayd",
    labelEn: "Zayd (ibn Ḥārithah)",
    labelAr: "زيد",
    category: "person",
    note: "The only one of the Prophet's companions named directly in the Qur'an (33:37).",
    sources: [rootlessLemma("زيد")],
  },
];

export const SPECIES_TOPICS: TopicDefinition[] = [
  {
    slug: "the-cow",
    labelEn: "The Cow",
    labelAr: "البقرة",
    category: "species",
    sources: [root("بقر")],
  },
  {
    slug: "the-camel",
    labelEn: "The Camel",
    labelAr: "الجمل والناقة",
    category: "species",
    note: "جمل's root also covers unrelated senses (\"beautiful\", \"altogether\"); filtered to the lemma جَمَل itself, alongside the separate words ناقة and بعير.",
    sources: [rootedLemma("جمل", "جمل"), root("نوق"), root("بعر")],
  },
  {
    slug: "sheep-and-goats",
    labelEn: "Sheep & Goats",
    labelAr: "الغنم والمعز",
    category: "species",
    note: "غنم's root also covers \"spoils of war\" (مغانم); filtered to the lemma غَنَم itself.",
    sources: [rootedLemma("غنم", "غنم"), root("معز")],
  },
  {
    slug: "donkeys-and-mules",
    labelEn: "Donkeys & Mules",
    labelAr: "الحمير والبغال",
    category: "species",
    note: "حمر's root also covers the color \"red\" (حُمْر); filtered to the lemma حِمار itself.",
    sources: [rootedLemma("حمر", "حمار"), root("بغل")],
  },
  {
    slug: "the-horse",
    labelEn: "The Horse",
    labelAr: "الخيل",
    category: "species",
    note: "خيل's root also covers unrelated senses (\"arrogant\", \"seemed\"); filtered to the lemma خَيْل itself.",
    sources: [rootedLemma("خيل", "خيل")],
  },
  {
    slug: "the-dog",
    labelEn: "The Dog",
    labelAr: "الكلب",
    category: "species",
    sources: [rootedLemma("كلب", "كلب")],
  },
  {
    slug: "the-wolf",
    labelEn: "The Wolf",
    labelAr: "الذئب",
    category: "species",
    sources: [root("ذأب")],
  },
  {
    slug: "the-crow",
    labelEn: "The Crow",
    labelAr: "الغراب",
    category: "species",
    note: "غرب's root also covers \"west/sunset\" (مغرب); filtered to the lemma غُراب itself.",
    sources: [rootedLemma("غرب", "غراب")],
  },
  {
    slug: "snakes-and-serpents",
    labelEn: "Snakes & Serpents",
    labelAr: "الحية والثعبان",
    category: "species",
    note: "حية's root حيي is overwhelmingly about \"life\" (حياة); filtered to just the lemma حَيَّة, alongside the separate word ثعبان.",
    sources: [rootedLemma("حيي", "حيه"), root("ثعب")],
  },
  {
    slug: "monkeys",
    labelEn: "Monkeys",
    labelAr: "القردة",
    category: "species",
    sources: [rootedLemma("قرد", "قرده")],
  },
  {
    slug: "the-pig",
    labelEn: "The Pig",
    labelAr: "الخنزير",
    category: "species",
    sources: [root("خنزر")],
  },
  {
    slug: "the-elephant",
    labelEn: "The Elephant",
    labelAr: "الفيل",
    category: "species",
    sources: [root("فيل")],
  },
  {
    slug: "the-whale",
    labelEn: "The Whale (Jonah's Fish)",
    labelAr: "الحوت",
    category: "species",
    sources: [root("حوت")],
  },
  {
    slug: "the-frog",
    labelEn: "The Frog",
    labelAr: "الضفدع",
    category: "species",
    sources: [rootedLemma("ضفدع", "ضفادع")],
  },
  {
    slug: "the-locust",
    labelEn: "The Locust",
    labelAr: "الجراد",
    category: "species",
    sources: [root("جرد")],
  },
  {
    slug: "lice",
    labelEn: "Lice",
    labelAr: "القمل",
    category: "species",
    sources: [root("قمل")],
  },
  {
    slug: "the-mosquito",
    labelEn: "The Mosquito",
    labelAr: "البعوضة",
    category: "species",
    note: "بعوضة shares its root بعض with the extremely common word \"some/part\", but the lemma بعوضة itself is used only for the insect.",
    sources: [rootedLemma("بعض", "بعوضه")],
  },
  {
    slug: "the-ant",
    labelEn: "The Ant",
    labelAr: "النملة",
    category: "species",
    note: "نمل's root also covers \"fingertips\" (أنامل); filtered to the ant-specific lemmas.",
    sources: [rootedLemma("نمل", "نمل"), rootedLemma("نمل", "نمله")],
  },
  {
    slug: "the-bee",
    labelEn: "The Bee",
    labelAr: "النحلة",
    category: "species",
    note: "نحل's root also covers \"a freely-given gift\" (نِحْلَة, e.g. a dowry); filtered to the lemma نَحْل itself.",
    sources: [rootedLemma("نحل", "نحل")],
  },
  {
    slug: "the-spider",
    labelEn: "The Spider",
    labelAr: "العنكبوت",
    category: "species",
    sources: [root("عنكب")],
  },
  {
    slug: "birds",
    labelEn: "Birds",
    labelAr: "الطير",
    category: "species",
    note: "طير's root also covers \"omen\" (طائر، تطيّر), a distinct classical sense; filtered to the lemma طَيْر itself.",
    sources: [rootedLemma("طير", "طير")],
  },
  {
    slug: "the-hoopoe",
    labelEn: "The Hoopoe",
    labelAr: "الهدهد",
    category: "species",
    sources: [root("هدهد")],
  },
  {
    slug: "the-date-palm",
    labelEn: "The Date Palm",
    labelAr: "النخلة",
    category: "species",
    sources: [root("نخل")],
  },
  {
    slug: "the-grapevine",
    labelEn: "The Grapevine",
    labelAr: "العنب",
    category: "species",
    sources: [root("عنب")],
  },
  {
    slug: "the-pomegranate",
    labelEn: "The Pomegranate",
    labelAr: "الرمان",
    category: "species",
    sources: [root("رمن")],
  },
  {
    slug: "the-fig",
    labelEn: "The Fig",
    labelAr: "التين",
    category: "species",
    sources: [root("تين")],
  },
  {
    slug: "the-olive",
    labelEn: "The Olive",
    labelAr: "الزيتون",
    category: "species",
    sources: [root("زيت")],
  },
  {
    slug: "the-lote-tree",
    labelEn: "The Lote Tree",
    labelAr: "السدرة",
    category: "species",
    sources: [root("سدر")],
  },
  {
    slug: "the-zaqqum-tree",
    labelEn: "The Zaqqūm Tree",
    labelAr: "الزقوم",
    category: "species",
    sources: [root("زقم")],
  },
  {
    slug: "acacia-and-banana-trees",
    labelEn: "Acacia & Banana Trees",
    labelAr: "الطلح",
    category: "species",
    sources: [root("طلح")],
  },
  {
    slug: "the-mustard-seed",
    labelEn: "The Mustard Seed",
    labelAr: "الخردل",
    category: "species",
    sources: [root("خردل")],
  },
];

export const GEOGRAPHY_TOPICS: TopicDefinition[] = [
  {
    slug: "makkah",
    labelEn: "Makkah",
    labelAr: "مكة وبكة",
    category: "geography",
    sources: [rootlessLemma("مكه"), rootlessLemma("بكه")],
  },
  {
    slug: "madinah",
    labelEn: "Al-Madīnah",
    labelAr: "المدينة ويثرب",
    category: "geography",
    note: "مدينة is also the ordinary word for \"a city\" in general, not always the Prophet's city specifically.",
    sources: [rootedLemma("مدن", "مدينه"), rootlessLemma("يثرب")],
  },
  {
    slug: "egypt",
    labelEn: "Egypt (Miṣr)",
    labelAr: "مصر",
    category: "geography",
    sources: [root("مصر")],
  },
  {
    slug: "sheba",
    labelEn: "Sheba (Sabaʾ)",
    labelAr: "سبأ",
    category: "geography",
    sources: [root("سبأ")],
  },
  {
    slug: "babylon",
    labelEn: "Babylon",
    labelAr: "بابل",
    category: "geography",
    sources: [rootlessLemma("بابل")],
  },
  {
    slug: "madyan",
    labelEn: "Madyan (Midian)",
    labelAr: "مدين",
    category: "geography",
    sources: [rootedLemma("مدن", "مدين")],
  },
  {
    slug: "al-ahqaf",
    labelEn: "Al-Aḥqāf",
    labelAr: "الأحقاف",
    category: "geography",
    sources: [root("حقف")],
  },
  {
    slug: "rome",
    labelEn: "Rome (Byzantium)",
    labelAr: "الروم",
    category: "geography",
    sources: [rootlessLemma("روم")],
  },
  {
    slug: "the-thicket",
    labelEn: "The Thicket (Aykah)",
    labelAr: "الأيكة",
    category: "geography",
    sources: [rootlessLemma("ايكه")],
  },
  {
    slug: "tuwa-valley",
    labelEn: "Ṭuwā Valley",
    labelAr: "طوى",
    category: "geography",
    sources: [rootedLemma("طوي", "طوي")],
  },
  {
    slug: "safa-and-marwah",
    labelEn: "Ṣafā & Marwah",
    labelAr: "الصفا والمروة",
    category: "geography",
    sources: [rootlessLemma("صفا"), rootedLemma("مرو", "مروه")],
  },
  {
    slug: "iram",
    labelEn: "Iram",
    labelAr: "إرم",
    category: "geography",
    sources: [rootlessLemma("ارم")],
  },
  {
    slug: "thamud",
    labelEn: "Thamūd",
    labelAr: "ثمود",
    category: "geography",
    sources: [rootlessLemma("ثمود")],
  },
  {
    slug: "quraysh",
    labelEn: "Quraysh",
    labelAr: "قريش",
    category: "geography",
    sources: [rootedLemma("قرش", "قريش")],
  },
  {
    slug: "children-of-israel",
    labelEn: "Children of Israel",
    labelAr: "بنو إسرائيل",
    category: "geography",
    sources: [rootlessLemma("اسرائيل")],
  },
  {
    slug: "gog-and-magog",
    labelEn: "Gog & Magog",
    labelAr: "يأجوج ومأجوج",
    category: "geography",
    sources: [rootlessLemma("ياجوج"), rootlessLemma("ماجوج")],
  },
];

export const GEOLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "mountains",
    labelEn: "Mountains",
    labelAr: "الجبال",
    category: "geology",
    sources: [rootedLemma("جبل", "جبل")],
  },
  {
    slug: "the-sea",
    labelEn: "The Sea",
    labelAr: "البحر",
    category: "geology",
    sources: [rootedLemma("بحر", "بحر")],
  },
  {
    slug: "rivers",
    labelEn: "Rivers",
    labelAr: "الأنهار",
    category: "geology",
    note: "نهر's root also covers \"daytime\" (نَهار), a much more common sense on the same root; filtered to the lemma نَهَر itself.",
    sources: [rootedLemma("نهر", "نهر")],
  },
  {
    slug: "mount-sinai",
    labelEn: "Mount Sinai (Al-Ṭūr)",
    labelAr: "الطور وسيناء",
    category: "geology",
    note: "طور's root also covers \"stages\" (أطوار); filtered to the lemma طُور itself.",
    sources: [rootedLemma("طور", "طور"), rootlessLemma("سيناء")],
  },
  {
    slug: "mount-judi",
    labelEn: "Mount Al-Jūdī",
    labelAr: "الجودي",
    category: "geology",
    sources: [rootedLemma("جود", "جودي")],
  },
  {
    slug: "stones-and-rocks",
    labelEn: "Stones & Rocks",
    labelAr: "الحجارة",
    category: "geology",
    sources: [rootedLemma("حجر", "حجاره")],
  },
];

export const METEOROLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "clouds",
    labelEn: "Clouds",
    labelAr: "السحاب والغمام",
    category: "meteorology",
    note: "Both roots also cover unrelated senses (\"dragged\", \"grief\"); filtered to the cloud-specific lemmas.",
    sources: [rootedLemma("سحب", "سحاب"), rootedLemma("غمم", "غمام")],
  },
  {
    slug: "rain",
    labelEn: "Rain",
    labelAr: "المطر والغيث",
    category: "meteorology",
    sources: [root("مطر"), root("غيث")],
  },
  {
    slug: "wind",
    labelEn: "Wind",
    labelAr: "الريح",
    category: "meteorology",
    note: "ريح's root روح is mostly about \"spirit/soul\" (روح) and other unrelated senses; filtered to the lemma رِيح itself.",
    sources: [rootedLemma("روح", "ريح")],
  },
  {
    slug: "thunder",
    labelEn: "Thunder",
    labelAr: "الرعد",
    category: "meteorology",
    sources: [root("رعد")],
  },
  {
    slug: "lightning",
    labelEn: "Lightning",
    labelAr: "البرق",
    category: "meteorology",
    note: "برق's root also covers \"vessels/goblets\" (أباريق), which is excluded; a small number of matches are the verb \"dazzled\" rather than the noun.",
    sources: [rootedLemma("برق", "برق")],
  },
  {
    slug: "hail",
    labelEn: "Hail",
    labelAr: "البرد",
    category: "meteorology",
    sources: [root("برد")],
  },
];

export const COSMOLOGY_TOPICS: TopicDefinition[] = [
  {
    slug: "the-sun",
    labelEn: "The Sun",
    labelAr: "الشمس",
    category: "cosmology",
    sources: [root("شمس")],
  },
  {
    slug: "the-moon",
    labelEn: "The Moon",
    labelAr: "القمر",
    category: "cosmology",
    sources: [root("قمر")],
  },
  {
    slug: "stars",
    labelEn: "Stars",
    labelAr: "النجم",
    category: "cosmology",
    sources: [root("نجم")],
  },
  {
    slug: "constellations",
    labelEn: "Constellations",
    labelAr: "البروج",
    category: "cosmology",
    note: "برج's root also covers \"to display one's adornment ostentatiously\" (تبرّج); filtered to the lemma بُرُوج itself.",
    sources: [rootedLemma("برج", "بروج")],
  },
  {
    slug: "sirius",
    labelEn: "Sirius (Ash-Shiʿrā)",
    labelAr: "الشعرى",
    category: "cosmology",
    note: "شعرى shares its root شعر with \"poetry\", \"hair\" and \"to perceive\"; the lemma شِعْرَى itself is used only for the star.",
    sources: [rootedLemma("شعر", "شعري")],
  },
  {
    slug: "the-sky-and-heavens",
    labelEn: "The Sky & Heavens",
    labelAr: "السماء",
    category: "cosmology",
    note: "سماء's root also covers \"name\" (اسم، سمّى), an unrelated sense; filtered to the lemma سَماء itself.",
    sources: [rootedLemma("سمو", "سماء")],
  },
];

export const COMMODITIES_TOPICS: TopicDefinition[] = [
  {
    slug: "iron",
    labelEn: "Iron",
    labelAr: "الحديد",
    category: "commodities",
    note: "حديد's root also covers \"limits/boundaries\" (حدود), a much more common sense on the same root; filtered to the lemma حَدِيد itself.",
    sources: [rootedLemma("حدد", "حديد")],
  },
  {
    slug: "silver",
    labelEn: "Silver",
    labelAr: "الفضة",
    category: "commodities",
    sources: [rootedLemma("فضض", "فضه")],
  },
  {
    slug: "pearls",
    labelEn: "Pearls",
    labelAr: "اللؤلؤ",
    category: "commodities",
    sources: [root("لؤلؤ")],
  },
  {
    slug: "coral",
    labelEn: "Coral",
    labelAr: "المرجان",
    category: "commodities",
    sources: [rootedLemma("مرج", "مرجان")],
  },
  {
    slug: "brass",
    labelEn: "Brass (Molten Copper)",
    labelAr: "النحاس",
    category: "commodities",
    sources: [rootedLemma("نحس", "نحاس")],
  },
  {
    slug: "silk",
    labelEn: "Silk",
    labelAr: "الحرير",
    category: "commodities",
    sources: [rootedLemma("حرر", "حرير")],
  },
  {
    slug: "musk",
    labelEn: "Musk",
    labelAr: "المسك",
    category: "commodities",
    sources: [rootedLemma("مسك", "مسك")],
  },
];

export const ALL_TOPICS: TopicDefinition[] = [
  ...THEME_TOPICS,
  ...PROPHET_TOPICS,
  ...PEOPLE_TOPICS,
  ...SPECIES_TOPICS,
  ...GEOGRAPHY_TOPICS,
  ...GEOLOGY_TOPICS,
  ...METEOROLOGY_TOPICS,
  ...COSMOLOGY_TOPICS,
  ...COMMODITIES_TOPICS,
];

export function findTopicBySlug(slug: string): TopicDefinition | undefined {
  return ALL_TOPICS.find((t) => t.slug === slug);
}
